import {expect,test,type Page} from '@playwright/test';

async function openWithStepUp(page:Page,request:import('@playwright/test').APIRequestContext){await page.goto('/__e2e/login/l4');await page.waitForURL('**/');await page.getByRole('link',{name:'账户安全',exact:true}).click();await page.getByRole('button',{name:'进行近期验证'}).click();const proof=(await (await request.get('http://127.0.0.1:3000/__e2e/totp/l4')).json()).proof;await page.getByLabel('验证码或恢复码').fill(proof);await page.getByRole('button',{name:'使用验证码确认'}).click();await expect(page.locator('.status-message')).toContainText('近期验证有效至');await page.getByRole('link',{name:'权限管理',exact:true}).click();await expect(page.getByRole('heading',{name:'员工账号'})).toBeVisible();}

test.describe('Dashboard browser E2E: staff account governance',()=>{
  test.beforeEach(async({request})=>{await request.post('http://127.0.0.1:3000/__e2e/reset');});
  test('DE2E-STF-001 another owner approves elevation then safely downgrades the staff account',async({page,request})=>{await openWithStepUp(page,request);let card=page.getByRole('article',{name:'员工 客服小白'});await expect(card).toContainText('待确认升级至 L3 运营');await card.getByRole('button',{name:'确认提权'}).click();await expect(page.locator('.status-notice')).toContainText('员工账号已更新');card=page.getByRole('article',{name:'员工 客服小白'});await expect(card).toContainText('L3 运营 · 权限 v5 · 活跃会话 0');await card.getByLabel('内部级别').selectOption('L2_SUPERVISOR');await card.getByLabel('操作原因').fill('SUPPORT_ROLE_CORRECTION');await card.getByRole('button',{name:'保存级别'}).click();await expect(page.getByRole('article',{name:'员工 客服小白'})).toContainText('L2 主管 · 权限 v6 · 活跃会话 0');const state=await (await request.get('http://127.0.0.1:3000/__e2e/state')).json();expect(state.staffAccounts[1]).toMatchObject({effectiveLevel:'L2_SUPERVISOR',pendingElevationLevel:null,permissionsVersion:6,activeSessions:0,status:'ACTIVE'});});
  test('DE2E-STF-002 the last active owner cannot revoke their own owner access',async({page,request})=>{await openWithStepUp(page,request);const ownerCard=page.getByRole('article',{name:'员工 店长 Alice'});await ownerCard.getByRole('button',{name:'撤销权限'}).click();await expect(page.locator('.status-notice')).toContainText('only active owner');const state=await (await request.get('http://127.0.0.1:3000/__e2e/state')).json();expect(state.staffAccounts[0]).toMatchObject({effectiveLevel:'L4_ADMIN_OWNER',status:'ACTIVE',permissionsVersion:1});});
});
