import { describe, expect, test } from 'vitest';
import { buildApiServer } from '@blackcat/api/server';
import { InMemoryServicePackageStore, type ServicePackageVersionRecord } from '@blackcat/api/service-packages';
import { InMemoryOrderRequirementStore } from '@blackcat/api/order-requirements';
import { InMemoryAuditSink, InMemoryIdempotencyStore } from '@blackcat/api/security';

const orderId='00000000-0000-0000-0000-000000108001';
const packageId='00000000-0000-0000-0000-000000108100';

describe('M10-US-08 service package API',()=>{
  test('lets L3 operations create, publish and retire immutable package versions through admin routes',async()=>{
    const store=fixture();const audit=new InMemoryAuditSink();const server=buildApiServer({env:{NODE_ENV:'development',DATABASE_URL:'',API_PORT:'0',API_BASE_URL:'http://localhost',BOT_SERVICE_TOKEN:'valid-bot-token'},security:{auditSink:audit,idempotencyStore:new InMemoryIdempotencyStore(),staffDirectory:{resolveByDiscord:()=>({staffId:'00000000-0000-0000-0000-000000108900',userId:'00000000-0000-0000-0000-000000108901',level:'L3_OPERATIONS',permissionsVersion:1,status:'ACTIVE'})}},servicePackages:{store,now:()=>new Date('2026-08-04T12:00:00Z')}});
    const created=await server.inject({method:'POST',url:'/api/v1/admin/service-packages',headers:adminHeaders('package:admin:create'),payload:{code:'DELTA_ESCORT',displayName:'三角洲轻松护航',description:'一只技术猫和一只聊天猫',currency:'CAT',activate:false,slots:[{serviceCatalogVersionId:'00000000-0000-0000-0000-000000108201',unitCount:1,customerNoteTemplate:'负责技术护航'},{serviceCatalogVersionId:'00000000-0000-0000-0000-000000108202',unitCount:1,customerNoteTemplate:'技术要求不高，会聊天就行'}],reasonCode:'NEW_PACKAGE_VERSION'}});expect(created.statusCode,created.body).toBe(201);expect(created.json().data).toMatchObject({code:'DELTA_ESCORT',version:2,status:'DRAFT',defaultCustomerPriceMinor:200,slots:[{position:1},{position:2}]});const versionId=created.json().data.id;
    const clientPriced=await server.inject({method:'POST',url:'/api/v1/admin/service-packages',headers:adminHeaders('package:admin:client-price'),payload:{code:'DELTA_ESCORT',displayName:'错误定价',description:'客户端不得决定套餐总价',defaultCustomerPriceMinor:1,currency:'CAT',activate:false,slots:[{serviceCatalogVersionId:'00000000-0000-0000-0000-000000108201',unitCount:1,customerNoteTemplate:null}],reasonCode:'NEW_PACKAGE_VERSION'}});expect(clientPriced.statusCode).toBe(400);
    const activated=await server.inject({method:'PATCH',url:`/api/v1/admin/service-packages/${versionId}`,headers:adminHeaders('package:admin:activate'),payload:{expectedStatus:'DRAFT',action:'ACTIVATE',reasonCode:'PUBLISH_PACKAGE'}});expect(activated.statusCode,activated.body).toBe(200);expect(activated.json().data).toMatchObject({id:versionId,status:'ACTIVE'});
    const listed=await server.inject({method:'GET',url:'/api/v1/admin/service-packages?limit=10',headers:adminHeaders()});expect(listed.statusCode,listed.body).toBe(200);expect(listed.json().data.items).toEqual(expect.arrayContaining([expect.objectContaining({id:packageId,status:'RETIRED'}),expect.objectContaining({id:versionId,status:'ACTIVE'})]));
    const detail=await server.inject({method:'GET',url:`/api/v1/admin/service-packages/${versionId}`,headers:adminHeaders()});expect(detail.statusCode,detail.body).toBe(200);expect(detail.json().data).toMatchObject({id:versionId,code:'DELTA_ESCORT',status:'ACTIVE',createdByStaffId:'00000000-0000-0000-0000-000000108900',createdAt:'2026-08-04T12:00:00.000Z',activatedAt:'2026-08-04T12:00:00.000Z',slots:[{position:1,customerUnitPriceMinor:100},{position:2,customerUnitPriceMinor:100}]});await server.close();
  });
  test('atomically replaces a basket with independently editable default slots and server price',async()=>{
    const store=fixture();const staged=store.apply({orderId,servicePackageVersionId:packageId,expectedOrderVersion:1,actorGuildId:'999999999999999999',actorDiscordUserId:'111111111111111111',idempotencyKey:'package:apply:unit:0001',now:new Date('2026-08-04T12:00:00Z')});
    expect(staged.data).toMatchObject({compositionMode:'PACKAGE_DEFAULT',derivedTotalMinor:200,requirements:[{requestedPlayerCount:1,service:'TECH'},{requestedPlayerCount:1,service:'TECH'}]});expect(new Set(staged.data.requirements.map(item=>item.sourcePackageSlotId)).size).toBe(2);await staged.commit({} as never);expect(store.orders[0]).toMatchObject({version:2,amountMinor:200,sourcePackageVersionId:packageId,compositionMode:'PACKAGE_DEFAULT'});expect(store.requirements.filter(item=>item.status==='ACTIVE')).toHaveLength(2);
  });

  test('lists, previews and applies packages while rejecting client price fields',async()=>{
    const store=fixture();const server=buildApiServer({env:{NODE_ENV:'development',DATABASE_URL:'',API_PORT:'0',API_BASE_URL:'http://localhost',BOT_SERVICE_TOKEN:'valid-bot-token'},security:{auditSink:new InMemoryAuditSink(),idempotencyStore:new InMemoryIdempotencyStore()},servicePackages:{store,now:()=>new Date('2026-08-04T12:00:00Z')}});
    const listed=await server.inject({method:'GET',url:'/api/v1/service-packages?game=delta',headers:headers()});expect(listed.statusCode,listed.body).toBe(200);expect(listed.json()).toMatchObject({data:{items:[{game:'DELTA',gameDisplayName:'三角洲行动',displayName:'三角洲护航',slots:[{serviceDisplayName:'技术护航'},{serviceDisplayName:'技术护航'}]}]}});const otherGame=await server.inject({method:'GET',url:'/api/v1/service-packages?game=VALORANT',headers:headers()});expect(otherGame.json()).toMatchObject({data:{items:[]}});
    const preview=await server.inject({method:'POST',url:`/api/v1/service-packages/${packageId}/preview`,headers:headers()});expect(preview.statusCode,preview.body).toBe(200);expect(preview.json()).toMatchObject({data:{derivedTotalMinor:200,compositionMode:'PACKAGE_DEFAULT'}});
    const invalid=await server.inject({method:'POST',url:`/api/v1/orders/${orderId}/package`,headers:headers('package:invalid:0001'),payload:{expectedOrderVersion:1,servicePackageVersionId:packageId,amountMinor:1}});expect(invalid.statusCode).toBe(400);expect(store.orders[0]?.version).toBe(1);
    const applied=await server.inject({method:'POST',url:`/api/v1/orders/${orderId}/package`,headers:headers('package:apply:http:0001'),payload:{expectedOrderVersion:1,servicePackageVersionId:packageId}});expect(applied.statusCode,applied.body).toBe(200);expect(applied.json()).toMatchObject({data:{derivedTotalMinor:200,requirements:[{requestedPlayerCount:1},{requestedPlayerCount:1}]}});await server.close();
  });

  test('changes only the selected slot, saves its note and switches to server-repriced CUSTOMIZED mode',async()=>{
    const requirement=fixture().requirements.find(item=>item.status==='ACTIVE')!;const order={id:orderId,guildId:'999999999999999999',customerDiscordUserId:'111111111111111111',status:'DRAFT',version:2,amountMinor:180,sourcePackageVersionId:packageId,compositionMode:'PACKAGE_DEFAULT' as const};const store=new InMemoryOrderRequirementStore({orders:[order],requirements:[{...requirement,sourcePackageSlotId:'00000000-0000-0000-0000-000000108102',customerNote:null}],catalogs:[{id:'00000000-0000-0000-0000-000000108299',status:'ACTIVE',game:'DELTA',gameDisplayName:'三角洲行动',service:'FUN',serviceDisplayName:'娱乐陪玩',region:'NA',regionDisplayName:'北美',billingUnitMinutes:60,customerUnitPriceMinor:35}]});
    const project=store.update({orderId,requirementId:requirement.id,actorGuildId:order.guildId,actorDiscordUserId:order.customerDiscordUserId,expectedOrderVersion:2,expectedRequirementVersion:1,action:'CHANGE_PROJECT',serviceCatalogVersionId:'00000000-0000-0000-0000-000000108299',unitCount:1,requestedPlayerCount:1,idempotencyKey:'package:custom:project',now:new Date('2026-08-04T12:01:00Z')});await project.commit({} as never);const note=store.update({orderId,requirementId:requirement.id,actorGuildId:order.guildId,actorDiscordUserId:order.customerDiscordUserId,expectedOrderVersion:3,expectedRequirementVersion:2,action:'CHANGE_NOTE',serviceCatalogVersionId:null,unitCount:null,requestedPlayerCount:null,customerNote:'技术要求不高，会聊天就行',idempotencyKey:'package:custom:note',now:new Date('2026-08-04T12:02:00Z')});await note.commit({} as never);expect(store.orders[0]).toMatchObject({compositionMode:'CUSTOMIZED',amountMinor:35,version:4});expect(store.requirements[0]).toMatchObject({service:'FUN',customerNote:'技术要求不高，会聊天就行',sourcePackageSlotId:'00000000-0000-0000-0000-000000108102'});
  });

  test('reports catalog subtotal and package adjustment without asking the client to calculate either',async()=>{
    const applied=fixture();const staged=applied.apply({orderId,servicePackageVersionId:packageId,expectedOrderVersion:1,actorGuildId:'999999999999999999',actorDiscordUserId:'111111111111111111',idempotencyKey:'package:price:apply',now:new Date('2026-08-04T12:00:00Z')});await staged.commit({} as never);
    const requirements=new InMemoryOrderRequirementStore({orders:applied.orders,requirements:applied.requirements,catalogs:[]});
    expect(requirements.list({orderId,actorGuildId:'999999999999999999',actorDiscordUserId:'111111111111111111',cursor:null,limit:10})).toMatchObject({catalogSubtotalMinor:200,packageAdjustmentMinor:0,derivedTotalMinor:200});
  });
});

function fixture(){return new InMemoryServicePackageStore({orders:[{id:orderId,guildId:'999999999999999999',customerDiscordUserId:'111111111111111111',status:'DRAFT',version:1,amountMinor:50,sourcePackageVersionId:null,compositionMode:null}],requirements:[{id:'00000000-0000-0000-0000-000000108009',orderId,sourcePackageSlotId:null,serviceCatalogVersionId:'00000000-0000-0000-0000-000000108019',game:'DELTA',gameDisplayName:'三角洲行动',service:'TECH',serviceDisplayName:'技术护航',region:null,regionDisplayName:null,billingUnitMinutes:60,unitCount:1,requestedPlayerCount:1,customerUnitPriceMinor:50,estimatedLinePriceMinor:50,filledPlayerCount:0,customerNote:null,status:'ACTIVE',version:1,createdAt:'2026-08-04T11:00:00Z',updatedAt:'2026-08-04T11:00:00Z'}],packages:[pkg()]});}
function pkg():ServicePackageVersionRecord{return{id:packageId,code:'DELTA_ESCORT',version:1,status:'ACTIVE',game:'DELTA',gameDisplayName:'三角洲行动',displayName:'三角洲护航',description:'两位技术猫猫护航',defaultCustomerPriceMinor:200,currency:'CAT',slots:[slot('00000000-0000-0000-0000-000000108101',1),slot('00000000-0000-0000-0000-000000108102',2)]};}
function slot(id:string,position:number){return{id,position,serviceCatalogVersionId:`00000000-0000-0000-0000-00000010820${position}`,game:'DELTA',gameDisplayName:'三角洲行动',service:'TECH',serviceDisplayName:'技术护航',region:'NA',regionDisplayName:'北美',billingUnitMinutes:60,unitCount:1,customerUnitPriceMinor:100,customerNoteTemplate:position===2?'可改成会聊天的娱乐陪玩':null};}
function headers(key='package:list:0001'){return{authorization:'Bearer valid-bot-token','x-client-source':'DISCORD_BOT','x-actor-discord-user-id':'111111111111111111','x-actor-guild-id':'999999999999999999','idempotency-key':key};}
function adminHeaders(key?:string){return{authorization:'Bearer valid-bot-token','x-client-source':'DASHBOARD','x-actor-discord-user-id':'911111111111111111','x-actor-guild-id':'999999999999999999',...(key?{'idempotency-key':key}:{})};}
