import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { readFileSync } from 'node:fs';
import { describe,expect,test } from 'vitest';
import { AdminBusinessPage } from '../apps/dashboard/src/AdminBusinessPage.js';
import { buildAdminActionRequest,buildAdminBusinessNavigation,buildAdminBusinessPage,resolveAdminBusinessPage } from '../apps/dashboard/src/admin-business.js';

describe('M10-US-08 Dashboard package management',()=>{
  test('exposes a permission-scoped service package workspace with versioned editing',()=>{expect(resolveAdminBusinessPage('/admin/service-packages')).toBe('servicePackages');expect(buildAdminBusinessNavigation(['catalog.read']).map(item=>item.label)).toContain('服务套餐');const model=buildAdminBusinessPage({page:'servicePackages',permissions:['catalog.read','catalog.manage'],status:'READY',items:[{id:'package-v1',status:'ACTIVE'}]});expect(model.actions.map(item=>item.id)).toEqual(['CREATE_PACKAGE_VERSION','COPY_PACKAGE_VERSION','UPDATE_PACKAGE_STATUS']);});
  test('builds strict create and lifecycle requests without order prices or payout rules',()=>{const created=buildAdminActionRequest({actionId:'CREATE_PACKAGE_VERSION',fields:{code:'delta_escort',displayName:'三角洲护航',description:'两只猫猫护航',defaultCustomerPriceMinor:'180',activate:true,slotsJson:JSON.stringify([{serviceCatalogVersionId:'catalog-a',unitCount:1,customerNoteTemplate:'负责技术护航'},{serviceCatalogVersionId:'catalog-b',unitCount:1,customerNoteTemplate:'技术要求不高，会聊天就行'}]),reasonCode:'CREATE_PACKAGE'}});expect(created).toEqual({method:'POST',path:'/api/v1/admin/service-packages',body:{code:'DELTA_ESCORT',displayName:'三角洲护航',description:'两只猫猫护航',defaultCustomerPriceMinor:180,currency:'CAT',activate:true,slots:[{serviceCatalogVersionId:'catalog-a',unitCount:1,customerNoteTemplate:'负责技术护航'},{serviceCatalogVersionId:'catalog-b',unitCount:1,customerNoteTemplate:'技术要求不高，会聊天就行'}],reasonCode:'CREATE_PACKAGE'}});expect(JSON.stringify(created.body)).not.toContain('playerPayout');const status=buildAdminActionRequest({actionId:'UPDATE_PACKAGE_STATUS',item:{id:'package-v2',version:2,status:'DRAFT'},fields:{action:'ACTIVATE',reasonCode:'PUBLISH_PACKAGE'}});expect(status.body).toEqual({expectedStatus:'DRAFT',action:'ACTIVATE',reasonCode:'PUBLISH_PACKAGE'});});
  test('renders an ordered slot editor with service selections, notes and server-pricing guidance',()=>{const model=buildAdminBusinessPage({page:'servicePackages',permissions:['catalog.read','catalog.manage'],status:'EMPTY'});const html=renderToStaticMarkup(createElement(AdminBusinessPage,{model,activeAction:{action:model.actions[0]!},serviceCatalogOptions:[{id:'catalog-a',gameDisplayName:'三角洲行动',serviceDisplayName:'技术护航',regionDisplayName:'北美'}],onSubmitAction:()=>undefined}));expect(html).toContain('默认陪玩席位');expect(html).toContain('三角洲行动 · 技术护航 · 北美');expect(html).toContain('添加陪玩席位');expect(html).toContain('name="slotsJson"');expect(html).toContain('留空时由 API 汇总席位目录价');});
  test('copies an existing package into the editor and creates a new immutable version',()=>{const model=buildAdminBusinessPage({page:'servicePackages',permissions:['catalog.read','catalog.manage'],status:'READY',items:[]});const action=model.actions.find((item)=>item.id==='COPY_PACKAGE_VERSION')!;const item={id:'package-v2',code:'DELTA_ESCORT',displayName:'三角洲护航',description:'一个技术位与一个聊天位',defaultCustomerPriceMinor:180,slots:[{serviceCatalogVersionId:'catalog-a',unitCount:1,customerNoteTemplate:'负责技术护航'}]};const html=renderToStaticMarkup(createElement(AdminBusinessPage,{model,activeAction:{action,item},serviceCatalogOptions:[{id:'catalog-a',gameDisplayName:'三角洲行动',serviceDisplayName:'技术护航'}],onSubmitAction:()=>undefined}));expect(html).toContain('编辑套餐（创建新版本）');expect(html).toContain('value="DELTA_ESCORT"');expect(html).toContain('一个技术位与一个聊天位');expect(html).toContain('负责技术护航');const request=buildAdminActionRequest({actionId:'COPY_PACKAGE_VERSION',item,fields:{code:'DELTA_ESCORT',displayName:'三角洲护航',description:'调整后的阵容',defaultCustomerPriceMinor:'200',slotsJson:JSON.stringify([{serviceCatalogVersionId:'catalog-a',unitCount:2,customerNoteTemplate:'双人技术护航'}]),reasonCode:'REVISE_PACKAGE'}});expect(request).toMatchObject({method:'POST',path:'/api/v1/admin/service-packages',body:{code:'DELTA_ESCORT',displayName:'三角洲护航',defaultCustomerPriceMinor:200}});});
  test('captures slot input values before React releases the change event',()=>{const source=readFileSync(new URL('../apps/dashboard/src/AdminBusinessPage.tsx',import.meta.url),'utf8');expect(source).not.toContain('serviceCatalogVersionId:event.currentTarget.value');expect(source).not.toContain('unitCount:Number(event.currentTarget.value)');expect(source).not.toContain('customerNoteTemplate:event.currentTarget.value');});
  test('keeps retired history visible without offering another lifecycle mutation',()=>{const model=buildAdminBusinessPage({page:'servicePackages',permissions:['catalog.read','catalog.manage'],status:'READY',items:[{id:'package-old',version:1,status:'RETIRED',displayName:'旧护航套餐'}]});const html=renderToStaticMarkup(createElement(AdminBusinessPage,{model,onAction:()=>undefined}));expect(html).toContain('旧护航套餐');expect(html).not.toContain('>发布或退役</button>');expect(html).not.toContain('未映射字段');});
});
