import {describe,expect,test} from 'vitest';
import {buildApiServer} from '@blackcat/api/server';
import {InMemoryReferralAttributionStore,calculateReferralCommissionMinor,registerReferralAttributionRoutes,type ReferralProgramPolicy} from '@blackcat/api/referrals';
import {InMemoryAuditSink,InMemoryIdempotencyStore,type StaffDirectory} from '@blackcat/api/security';

const now=new Date('2026-07-18T21:00:00Z');const customerId='00000000-0000-0000-0000-000000004510';const beneficiaryId='00000000-0000-0000-0000-000000004511';
const policies:ReferralProgramPolicy[]=[{id:'00000000-0000-0000-0000-000000004520',programType:'PROMOTER_FIRST_PURCHASE',version:1,rewardMode:'PERCENT_FIRST_PURCHASE',rateBps:500,fixedAmountMinor:null,currency:'USD'},
{id:'00000000-0000-0000-0000-000000004521',programType:'PLAYER_LIFETIME',version:1,rewardMode:'PERCENT_LIFETIME',rateBps:200,fixedAmountMinor:null,currency:'USD'}];
function headers(key?:string){return{authorization:'Bearer valid-bot-token','x-client-source':'DASHBOARD','x-actor-discord-user-id':'900000000000000071','x-actor-guild-id':'900000000000000001','x-discord-interaction-id':'900000000000000072',...(key?{'idempotency-key':key}:{})};}
function fixture(level:'L1_SUPPORT'|'L2_SUPERVISOR'|'L3_OPERATIONS',stepUp=false,input:{consumed?:string[]}={}){const store=new InMemoryReferralAttributionStore({users:[customerId,beneficiaryId,'00000000-0000-0000-0000-000000004512'],playerUsers:[beneficiaryId,'00000000-0000-0000-0000-000000004512'],policies,consumedUsers:input.consumed});
 const directory:StaffDirectory={resolveByDiscord:()=>({staffId:'00000000-0000-0000-0000-000000004513',userId:'00000000-0000-0000-0000-000000004513',level,status:'ACTIVE',permissionsVersion:1})};
 const server=buildApiServer({env:{NODE_ENV:'development',DATABASE_URL:'',API_PORT:'0',API_BASE_URL:'http://localhost:3000',BOT_SERVICE_TOKEN:'valid-bot-token'},security:{staffDirectory:directory,auditSink:new InMemoryAuditSink(),idempotencyStore:new InMemoryIdempotencyStore(),stepUpVerifier:{verify:()=>stepUp}}});registerReferralAttributionRoutes(server,{store,now:()=>now});return{server,store};}
const createPayload={referredCustomerId:customerId,beneficiaryId,programType:'PLAYER_LIFETIME',bindingMethod:'ADMIN_MANUAL',reasonCode:'VERIFIED_MANUAL_BINDING'};
describe('M3-US-07 confidential referral attribution',()=>{
 test('uses integer floor rounding for percentage awards',()=>{expect(calculateReferralCommissionMinor({baseAmountMinor:12345,awardMode:'NET_SPEND_BPS',fixedAmountMinor:null,rateBps:500})).toBe(617);});
 test('allows L2 only the redacted list',async()=>{const l1=fixture('L1_SUPPORT');expect((await l1.server.inject({method:'GET',url:'/api/v1/admin/referral-attributions',headers:headers()})).statusCode).toBe(403);
  const l2=fixture('L2_SUPERVISOR');expect((await l2.server.inject({method:'POST',url:'/api/v1/admin/referral-attributions',headers:headers('ref:l2:deny:0001'),payload:createPayload})).statusCode).toBe(403);});
 test('requires L3 step-up and resolves policy on the server',async()=>{expect((await fixture('L3_OPERATIONS').server.inject({method:'POST',url:'/api/v1/admin/referral-attributions',headers:headers('ref:no-step:0001'),payload:createPayload})).statusCode).toBe(428);
  const {server}=fixture('L3_OPERATIONS',true);expect((await server.inject({method:'POST',url:'/api/v1/admin/referral-attributions',headers:headers('ref:client-rate:0001'),payload:{...createPayload,rateBps:9999}})).statusCode).toBe(400);
  const response=await server.inject({method:'POST',url:'/api/v1/admin/referral-attributions',headers:headers('ref:create:4510:0001'),payload:createPayload});
  expect(response.statusCode).toBe(201);expect(response.json()).toMatchObject({data:{referredCustomerId:customerId,beneficiaryId,programType:'PLAYER_LIFETIME',rewardMode:'PERCENT_LIFETIME',rateBps:200,status:'ACTIVE'}});});
 test('rejects self, duplicate, and late attribution',async()=>{const self=fixture('L3_OPERATIONS',true);expect((await self.server.inject({method:'POST',url:'/api/v1/admin/referral-attributions',headers:headers('ref:self:deny:0001'),payload:{...createPayload,beneficiaryId:customerId}})).statusCode).toBe(422);
  const late=fixture('L3_OPERATIONS',true,{consumed:[customerId]});expect((await late.server.inject({method:'POST',url:'/api/v1/admin/referral-attributions',headers:headers('ref:late:deny:0001'),payload:createPayload})).statusCode).toBe(422);
  const f=fixture('L3_OPERATIONS',true);await f.server.inject({method:'POST',url:'/api/v1/admin/referral-attributions',headers:headers('ref:first:create:0001'),payload:createPayload});expect((await f.server.inject({method:'POST',url:'/api/v1/admin/referral-attributions',headers:headers('ref:duplicate:0001'),payload:{...createPayload,programType:'PROMOTER_FIRST_PURCHASE'}})).statusCode).toBe(422);});
 test('shows L2 only redacted records and corrects by appending a replacement',async()=>{const f=fixture('L3_OPERATIONS',true);const created=await f.server.inject({method:'POST',url:'/api/v1/admin/referral-attributions',headers:headers('ref:create:correct'),payload:createPayload});const id=created.json().data.id;
  const corrected=await f.server.inject({method:'PATCH',url:`/api/v1/admin/referral-attributions/${id}`,headers:headers('ref:correct:4510'),payload:{expectedVersion:1,replacementBeneficiaryId:'00000000-0000-0000-0000-000000004512',reasonCode:'ATTRIBUTION_EVIDENCE_CORRECTED'}});
  expect(corrected.json()).toMatchObject({data:{status:'ACTIVE',beneficiaryId:'00000000-0000-0000-0000-000000004512',bindingMethod:'ADMIN_CORRECTION'}});expect(f.store.attributions).toHaveLength(2);expect(f.store.attributions[0]).toMatchObject({status:'SUPERSEDED'});
  const l2=fixture('L2_SUPERVISOR');l2.store.attributions.push(...structuredClone(f.store.attributions));const list=await l2.server.inject({method:'GET',url:'/api/v1/admin/referral-attributions',headers:headers()});expect(list.json().data.items).toHaveLength(2);expect(list.json().data.items[0]).toMatchObject({id:expect.any(String),attentionRequired:false});expect(JSON.stringify(list.json())).not.toContain(customerId);});
});
