import { useState } from 'react';
import { formatMinorCurrency, minorToCatInput, readAdminOrderTimeline, type AdminBusinessDetailState } from './admin-business.js';
import { dashboardFieldLabel } from './table-labels.js';
import { catalogStatusLabel, displayValue, formatOrderDate, formatRelativeDate, numberValue, orderOperationalState, orderPrice, orderStatusLabel, OrderFact, priceValue, scalarValue, textValue } from './admin-business-presenters.js';

export function AdminBusinessDetail(props: { detail: AdminBusinessDetailState; onClose?: () => void; onNextConsumptions?: (cursor: string) => void; onNextTimeline?: (cursor: string) => void;onNextTranscript?:(cursor:string)=>void;serviceCatalogOptions?:Array<Record<string,unknown>>;participantPlayerOptions?:Array<Record<string,unknown>>;participantMutationError?:string|null;onAddOrderParticipant?:(fields:Record<string,unknown>)=>void;onUpdateOrderParticipant?:(fields:Record<string,unknown>)=>void;onUpdateOrderNote?:(fields:Record<string,unknown>)=>void;onUpdateOrderRequirement?:(fields:Record<string,unknown>)=>void }) {
  const { detail } = props;
  return (
    <aside className="content-panel detail-panel" aria-label="业务对象详情">
      <div className="panel-heading"><h2>详情</h2><button type="button" onClick={props.onClose}>关闭</button></div>
      {detail.kind === 'LOADING' && <p aria-busy="true">正在载入详情...</p>}
      {detail.kind === 'FORBIDDEN' && <p role="alert">{detail.page === 'orders' ? '当前订单不在你的任务权限范围内。' : '当前账号无权查看此详情。'}{detail.requestId ? ` 请求编号：${detail.requestId}` : ''}</p>}
      {detail.kind === 'ERROR' && <p role="alert">详情暂时无法载入。{detail.requestId ? ` 请求编号：${detail.requestId}` : ''}</p>}
      {detail.kind === 'READY' && detail.data && <>{detail.page === 'orders' ? <OrderTimelineRegion data={detail.data} pageState={detail.timelinePage} transcriptState={detail.transcriptPage} onNext={props.onNextTimeline} onNextTranscript={props.onNextTranscript} serviceCatalogOptions={props.serviceCatalogOptions??[]} participantPlayerOptions={props.participantPlayerOptions??[]} mutationError={props.participantMutationError} onAdd={props.onAddOrderParticipant} onUpdate={props.onUpdateOrderParticipant} onUpdateOrderNote={props.onUpdateOrderNote} onUpdateRequirement={props.onUpdateOrderRequirement} /> : <StructuredAdminDetail page={detail.page} data={detail.data} />}{detail.page === 'users' && detail.consumptions && <UserConsumptionRegion consumptions={detail.consumptions} onNext={props.onNextConsumptions} />}</>}
    </aside>
  );
}

function StructuredAdminDetail({ page, data }: { page: Exclude<AdminBusinessDetailState['page'], 'orders'>; data: Record<string, unknown> }) {
  if (page === 'users') return <CustomerDetail data={data} />;
  if (page === 'players') return <PlayerProfileDetail data={data} />;
  if (page === 'serviceCatalog') return <CatalogDetail data={data} />;
  if (page === 'servicePackages') return <PackageDetail data={data} />;
  if (page === 'giftCatalog') return <GiftCatalogDetail data={data} />;
  if (page === 'giftRequests') return <GiftRequestDetail data={data} />;
  return <dl className="definition-list">{Object.entries(data).map(([key, value]) => <div key={key}><dt><strong>{dashboardFieldLabel(key)}</strong></dt><dd>{displayValue(key, value, data.currency)}</dd></div>)}</dl>;
}

function DetailStatus({ status }: { status: string }) {
  return <span className={`entity-detail__status entity-detail__status--${status.toLowerCase()}`}>{catalogStatusLabel(status)}</span>;
}

function DetailFacts({ facts }: { facts: Array<{ label: string; value: string; strong?: boolean; mono?: boolean }> }) {
  return <dl className="entity-detail__facts">{facts.map((fact) => <div key={fact.label}><dt>{fact.label}</dt><dd className={`${fact.strong ? 'is-strong' : ''} ${fact.mono ? 'is-mono' : ''}`.trim()}>{fact.value}</dd></div>)}</dl>;
}

function DetailTags({ values, empty = '未配置' }: { values: unknown; empty?: string }) {
  const tags = Array.isArray(values) ? values.map((value) => value && typeof value === 'object' && !Array.isArray(value) ? textValue((value as Record<string, unknown>).displayName) || textValue((value as Record<string, unknown>).code) : textValue(value)).filter(Boolean) : textValue(values).split(',').map((item) => item.trim()).filter(Boolean);
  return tags.length ? <div className="entity-detail__tags">{tags.map((tag) => <span key={tag}>{tag}</span>)}</div> : <p className="entity-detail__empty">{empty}</p>;
}

function CustomerDetail({ data }: { data: Record<string, unknown> }) {
  const status = textValue(data.status);
  const riskFlags = Array.isArray(data.riskFlags) ? data.riskFlags : textValue(data.riskFlags) ? [textValue(data.riskFlags)] : [];
  return <div className="entity-detail customer-detail">
    <header className="entity-detail__hero"><div><span className="entity-detail__eyebrow">客户概览</span><h3>{textValue(data.displayName) || '未命名客户'}</h3><p>{textValue(data.discordUsername) ? `Discord · ${textValue(data.discordUsername)}` : 'Discord 身份未绑定'}</p></div>{status && <DetailStatus status={status} />}</header>
    <div className="entity-detail__layout"><section className="entity-detail__section"><div className="entity-detail__section-heading"><div><span>ACCOUNT</span><h4>账户与运营</h4></div></div><DetailFacts facts={[{ label: '客户编号', value: textValue(data.id) || '—', mono: true }, { label: 'Discord 用户编号', value: textValue(data.discordUserId) || '—', mono: true }, { label: '外部账户摘要', value: textValue(data.externalAccountDisplay) || '—' }, { label: '进行中订单', value: textValue(data.activeOrderId) || '无' }, { label: '风险标记', value: riskFlags.length ? `${riskFlags.length} 项` : '无' }, { label: '数据版本', value: scalarValue(data.version) }, { label: '创建时间', value: scalarValue(data.createdAt) }, { label: '更新时间', value: scalarValue(data.updatedAt) }]} />{riskFlags.length > 0 && <DetailTags values={riskFlags} />}</section>
      <aside className="entity-detail__aside"><span className="entity-detail__aside-label">CUSTOMER PROFILE</span><h4>查看完整客户资料</h4><p>余额、订单、消费与风险模块会在独立档案中按权限展示。</p>{typeof data.id === 'string' && <a className="entity-detail__link" href={`/admin/users/${encodeURIComponent(data.id)}/profile`}>打开完整客户档案 <span aria-hidden="true">→</span></a>}</aside></div>
  </div>;
}

function PlayerProfileDetail({ data }: { data: Record<string, unknown> }) {
  const status = textValue(data.reviewStatus);
  return <div className="entity-detail player-profile-detail">
    <header className="entity-detail__hero"><div><span className="entity-detail__eyebrow">陪玩档案</span><h3>{textValue(data.displayName) || '未命名陪玩'}</h3><p>{textValue(data.discordUsername) ? `Discord · ${textValue(data.discordUsername)}` : 'Discord 身份未绑定'}</p></div>{status && <DetailStatus status={status} />}</header>
    <div className="entity-detail__layout"><section className="entity-detail__section"><div className="entity-detail__section-heading"><div><span>SERVICE RANGE</span><h4>支持范围</h4></div></div><div className="entity-detail__tag-groups"><div><h5>游戏</h5><DetailTags values={data.gameTagDetails ?? data.gameTags} /></div><div><h5>服务</h5><DetailTags values={data.serviceTagDetails ?? data.serviceTags} /></div><div><h5>语言</h5><DetailTags values={data.languageTagDetails ?? data.languageTags} /></div></div></section>
      <section className="entity-detail__section"><div className="entity-detail__section-heading"><div><span>IDENTITY</span><h4>账号与状态</h4></div></div><DetailFacts facts={[{ label: '陪玩编号', value: textValue(data.playerId) || '—', mono: true }, { label: '用户编号', value: textValue(data.userId) || '—', mono: true }, { label: 'Discord 用户编号', value: textValue(data.discordUserId) || '—', mono: true }, { label: '审核状态', value: status || '—' }, { label: '历史接单状态（参考）', value: textValue(data.availability) || '—' }, { label: 'Discord 在线状态（参考）', value: textValue(data.discordPresence) || '—' }, { label: '进行中订单', value: textValue(data.activeOrderId) || '无' }, { label: '数据版本', value: scalarValue(data.version) }, { label: '创建时间', value: scalarValue(data.createdAt) }, { label: '更新时间', value: scalarValue(data.updatedAt) }]} /></section></div>
  </div>;
}

function CatalogDetail({ data }: { data: Record<string, unknown> }) {
  const status = textValue(data.status) || (data.enabled === false ? 'INACTIVE' : 'ACTIVE');
  const currency = textValue(data.currency) || 'CAT';
  const game = textValue(data.gameDisplayName) || textValue(data.game) || '未指定游戏';
  const service = textValue(data.serviceDisplayName) || textValue(data.service) || '未指定服务';
  const payoutBps = numberValue(data.defaultPlayerPayoutBps);
  return <div className="entity-detail catalog-detail">
    <header className="entity-detail__hero entity-detail__hero--catalog"><div><span className="entity-detail__eyebrow">服务项目</span><h3>{game} <span>·</span> {service}</h3><p>{textValue(data.regionDisplayName) || textValue(data.region) || '不限区服'} · 版本 {scalarValue(data.version)}</p></div><DetailStatus status={status} /></header>
    <section className="entity-detail__price-strip" aria-label="价格与计费概览"><div><span>客户单价</span><strong>{priceValue(data.customerUnitPriceMinor, currency)}</strong></div><div><span>计费单位</span><strong>{numberValue(data.billingUnitMinutes) ? `${numberValue(data.billingUnitMinutes)} 分钟` : '—'}</strong></div><div><span>最低购买</span><strong>{numberValue(data.minimumUnits) ? `${numberValue(data.minimumUnits)} 单位` : '—'}</strong></div></section>
    <div className="entity-detail__layout"><section className="entity-detail__section"><div className="entity-detail__section-heading"><div><span>PRICING</span><h4>价格与计费</h4></div></div><DetailFacts facts={[{ label: '客户单位价格', value: priceValue(data.customerUnitPriceMinor, currency), strong: true }, { label: '默认陪玩分成', value: payoutBps == null ? '未配置' : `${payoutBps / 100}%` }, { label: '结算币种', value: currency }, { label: '最低购买单位', value: numberValue(data.minimumUnits) ? `${numberValue(data.minimumUnits)} 单位` : '—' }]} /></section>
      <section className="entity-detail__section"><div className="entity-detail__section-heading"><div><span>IDENTIFIERS</span><h4>目录标识与审计</h4></div></div><DetailFacts facts={[{ label: '稳定代码', value: textValue(data.offeringKey) || textValue(data.code) || '—', mono: true }, { label: '服务项目编号', value: textValue(data.serviceOfferingId) || '—', mono: true }, { label: '目录版本编号', value: textValue(data.id) || '—', mono: true }, { label: '创建员工', value: textValue(data.createdByStaffId) || '—', mono: true }, { label: '创建时间', value: scalarValue(data.createdAt) }, { label: '激活时间', value: scalarValue(data.activatedAt) }, { label: '退役时间', value: scalarValue(data.retiredAt) }]} /></section></div>
  </div>;
}

function PackageDetail({ data }: { data: Record<string, unknown> }) {
  const status = textValue(data.status) || 'DRAFT';
  const currency = textValue(data.currency) || 'CAT';
  const slots = Array.isArray(data.slots) ? data.slots.filter((slot): slot is Record<string, unknown> => Boolean(slot && typeof slot === 'object' && !Array.isArray(slot))) : [];
  return <div className="entity-detail package-detail">
    <header className="entity-detail__hero entity-detail__hero--package"><div><span className="entity-detail__eyebrow">套餐概览</span><h3>{textValue(data.displayName) || textValue(data.code) || '未命名套餐'}</h3><p>{textValue(data.gameDisplayName) || textValue(data.game) || '游戏归属待确认'} · {slots.length} 个独立席位 · 版本 {scalarValue(data.version)}</p></div><DetailStatus status={status} /></header>
    <section className="entity-detail__package-intro"><div><span>套餐说明</span><p>{textValue(data.description) || '暂未填写套餐说明。'}</p></div><div><span>套餐价格</span><strong>{priceValue(data.defaultCustomerPriceMinor, currency)}</strong><small>按席位目录价格汇总</small></div></section>
    <section className="entity-detail__section entity-detail__section--slots"><div className="entity-detail__section-heading"><div><span>LINEUP</span><h4>套餐席位</h4></div><strong>{slots.length} 个席位</strong></div>{slots.length ? <div className="package-detail__slots">{slots.map((slot, index) => { const position = numberValue(slot.position) ?? index + 1; return <article className="package-detail__slot" aria-label={`${position} 号位`} key={textValue(slot.id) || `${index}`}><div className="package-detail__slot-index"><span>{position}</span><small>号位</small></div><div className="package-detail__slot-main"><h5>{textValue(slot.serviceDisplayName) || textValue(slot.service) || '未指定服务'}</h5><p>{[textValue(slot.gameDisplayName) || textValue(slot.game), textValue(slot.regionDisplayName) || textValue(slot.region) || '不限区服'].filter(Boolean).join(' · ')}</p><div className="package-detail__slot-meta"><span>{numberValue(slot.unitCount) ?? '—'} 个计费单位</span><span>{numberValue(slot.billingUnitMinutes) ?? '—'} 分钟 / 单位</span></div>{textValue(slot.customerNoteTemplate) && <blockquote>{textValue(slot.customerNoteTemplate)}</blockquote>}</div></article>; })}</div> : <p className="entity-detail__empty">尚未配置套餐席位。</p>}</section>
    <section className="entity-detail__section entity-detail__section--identifiers"><div className="entity-detail__section-heading"><div><span>VERSION</span><h4>版本与审计</h4></div></div><DetailFacts facts={[{ label: '稳定套餐代码', value: textValue(data.code) || '—', mono: true }, { label: '套餐版本编号', value: textValue(data.id) || '—', mono: true }, { label: '数据版本', value: scalarValue(data.version) }, { label: '状态', value: catalogStatusLabel(status) }, { label: '创建员工', value: textValue(data.createdByStaffId) || '—', mono: true }, { label: '创建时间', value: scalarValue(data.createdAt) }, { label: '激活时间', value: scalarValue(data.activatedAt) }, { label: '退役时间', value: scalarValue(data.retiredAt) }]} /></section>
  </div>;
}

function GiftCatalogDetail({ data }: { data: Record<string, unknown> }) {
  const status = textValue(data.status);
  const category = data.giftCategoryTagDetails && typeof data.giftCategoryTagDetails === 'object' ? data.giftCategoryTagDetails as Record<string, unknown> : null;
  return <div className="entity-detail gift-catalog-detail">
    <header className="entity-detail__hero"><div><span className="entity-detail__eyebrow">礼物目录版本</span><h3>{textValue(data.name) || '未命名礼物'}</h3><p>{textValue(data.code) || '—'} · 版本 {scalarValue(data.version)}</p></div>{status && <DetailStatus status={status} />}</header>
    <section className="entity-detail__price-strip" aria-label="礼物价格概览"><div><span>客户价格</span><strong>{priceValue(data.priceMinor, textValue(data.currency) || 'CAT')}</strong></div><div><span>礼物分类</span><strong>{textValue(category?.displayName) || '未分类'}</strong></div><div><span>启用状态</span><strong>{data.enabled === true ? '已启用' : data.enabled === false ? '未启用' : '—'}</strong></div></section>
    <div className="entity-detail__layout"><section className="entity-detail__section"><div className="entity-detail__section-heading"><div><span>CONTENT</span><h4>播报与分类</h4></div></div><DetailFacts facts={[{label:'礼物分类代码',value:textValue(category?.code)||'—',mono:true},{label:'分类编号',value:textValue(data.giftCategoryTagId)||'—',mono:true},{label:'播报模板',value:textValue(data.broadcastTemplate)||'—'}]} /></section>
      <section className="entity-detail__section"><div className="entity-detail__section-heading"><div><span>VERSION</span><h4>版本与审计</h4></div></div><DetailFacts facts={[{label:'礼物目录编号',value:textValue(data.id)||'—',mono:true},{label:'礼物版本编号',value:textValue(data.giftCatalogVersionId)||'—',mono:true},{label:'创建员工',value:textValue(data.createdByStaffId)||'—',mono:true},{label:'创建时间',value:scalarValue(data.createdAt)},{label:'激活时间',value:scalarValue(data.activatedAt)},{label:'退役时间',value:scalarValue(data.retiredAt)},{label:'归档时间',value:scalarValue(data.archivedAt)}]} /></section></div>
  </div>;
}

function GiftRequestDetail({ data }: { data: Record<string, unknown> }) {
  const status = textValue(data.status);
  return <div className="entity-detail gift-request-detail">
    <header className="entity-detail__hero"><div><span className="entity-detail__eyebrow">送礼审核</span><h3>礼物请求 {textValue(data.publicId) || '—'}</h3><p>{textValue(data.giftName) || '未命名礼物'} · {priceValue(data.amountMinor, textValue(data.currency) || 'CAT')}</p></div>{status && <DetailStatus status={status} />}</header>
    <section className="entity-detail__price-strip" aria-label="礼物请求概览"><div><span>来源订单</span><strong>{textValue(data.orderPublicId) || '—'}</strong></div><div><span>预留状态</span><strong>{textValue(data.reservationStatus) || '无预留'}</strong></div><div><span>播报状态</span><strong>{textValue(data.announcementStatus) || '—'}</strong></div></section>
    <div className="entity-detail__layout"><section className="entity-detail__section"><div className="entity-detail__section-heading"><div><span>PARTIES</span><h4>用户与目标陪玩</h4></div></div><DetailFacts facts={[{label:'用户',value:textValue(data.senderDisplayName)||'—',strong:true},{label:'用户 Discord',value:textValue(data.senderDiscordUsername)||textValue(data.senderDiscordUserId)||'—'},{label:'目标陪玩',value:textValue(data.receiverDisplayName)||'—',strong:true},{label:'陪玩 Discord',value:textValue(data.receiverDiscordUsername)||textValue(data.receiverDiscordUserId)||'—'},{label:'订单编号',value:textValue(data.orderId)||'—',mono:true},{label:'订单参与人编号',value:textValue(data.orderParticipantId)||'—',mono:true}]} /></section>
      <section className="entity-detail__section"><div className="entity-detail__section-heading"><div><span>REVIEW</span><h4>审核与资金</h4></div></div><DetailFacts facts={[{label:'预留编号',value:textValue(data.reservationId)||'—',mono:true},{label:'预留有效至',value:scalarValue(data.reservationExpiresAt)},{label:'核对员工',value:textValue(data.verifiedByStaffId)||'—',mono:true},{label:'核对时间',value:scalarValue(data.verifiedAt)},{label:'核对备注',value:textValue(data.verificationNote)||'—'},{label:'批准员工',value:textValue(data.approvedByStaffId)||'—',mono:true},{label:'批准时间',value:scalarValue(data.approvedAt)},{label:'捕获时间',value:scalarValue(data.capturedAt)}]} /></section></div>
    <section className="entity-detail__section"><div className="entity-detail__section-heading"><div><span>DELIVERY</span><h4>播报与生命周期</h4></div></div><DetailFacts facts={[{label:'当时使用的播报模板',value:textValue(data.broadcastTemplate)||'—'},{label:'礼物代码',value:textValue(data.giftCode)||'—',mono:true},{label:'礼物版本编号',value:textValue(data.giftCatalogVersionId)||'—',mono:true},{label:'播报时间',value:scalarValue(data.announcedAt)},{label:'播报频道',value:textValue(data.broadcastChannelId)||'—',mono:true},{label:'播报消息',value:textValue(data.broadcastMessageId)||'—',mono:true},{label:'拒绝原因',value:textValue(data.rejectedReason)||'—'},{label:'失败代码',value:textValue(data.failureCode)||'—',mono:true},{label:'请求有效至',value:scalarValue(data.expiresAt)},{label:'撤回时间',value:scalarValue(data.withdrawnAt)},{label:'创建时间',value:scalarValue(data.createdAt)},{label:'更新时间',value:scalarValue(data.updatedAt)},{label:'数据版本',value:scalarValue(data.rowVersion)}]} /></section>
  </div>;
}

function OrderTimelineRegion(props:{data:Record<string,unknown>;pageState?:AdminBusinessDetailState['timelinePage'];transcriptState?:AdminBusinessDetailState['transcriptPage'];onNext?:(cursor:string)=>void;onNextTranscript?:(cursor:string)=>void;serviceCatalogOptions:Array<Record<string,unknown>>;participantPlayerOptions:Array<Record<string,unknown>>;mutationError?:string|null;onAdd?:(fields:Record<string,unknown>)=>void;onUpdate?:(fields:Record<string,unknown>)=>void;onUpdateOrderNote?:(fields:Record<string,unknown>)=>void;onUpdateRequirement?:(fields:Record<string,unknown>)=>void}) {
  const timeline=readAdminOrderTimeline(props.data);const order=props.data.order as Record<string,unknown>|undefined;const participantPage=props.data.participants as {items?:Array<Record<string,unknown>>;derivedTotalMinor?:unknown}|undefined;const participants=participantPage?.items??[];const requirementPage=props.data.requirements as {items?:Array<Record<string,unknown>>;derivedTotalMinor?:unknown;catalogSubtotalMinor?:unknown;packageAdjustmentMinor?:unknown}|undefined;
  const status=textValue(order?.status);const mutable=!['COMPLETED','CANCELLED'].includes(status);const operational=orderOperationalState(status);const customerName=textValue(order?.customerDisplayName)||textValue(order?.customerDiscordTag)||'客户资料待补充';const serviceSummary=textValue(order?.serviceSummary)||participants.map((participant)=>[textValue(participant.gameDisplayName),textValue(participant.serviceDisplayName)].filter(Boolean).join(' · ')).filter(Boolean).join('；')||'项目资料待补充';
  return <><section className="order-detail-summary order-operational-overview" aria-label="订单处理概览"><div className="subsection-heading"><div><span className="page-eyebrow">订单处理概览</span><h3>订单 {textValue(order?.publicId)||'—'}</h3></div><span className={`order-status order-status--${textValue(order?.status).toLowerCase()}`}>{orderStatusLabel(textValue(order?.status))}</span></div><dl className="order-operational-overview__facts"><OrderFact label="当前阻塞" value={operational.blocker}/><OrderFact label="下一步" value={operational.nextAction} strong/><OrderFact label="客户" value={customerName}/><OrderFact label="服务" value={serviceSummary}/><OrderFact label="订单金额" value={orderPrice(order??{})} strong/><OrderFact label="最近更新" value={`${formatRelativeDate(order?.updatedAt)} · ${formatOrderDate(order?.updatedAt)}`}/></dl>{textValue(order?.notes)&&<p>客户备注：{textValue(order?.notes)}</p>}</section>
    {mutable&&props.onUpdateOrderNote?<OrderNoteEditor note={textValue(order?.notes)} onSubmit={props.onUpdateOrderNote}/>:null}
    <details className="order-technical-details"><summary>订单标识与审计信息</summary><dl className="definition-list">{order&&Object.entries(order).filter(([key])=>['id','customerId','customerDiscordUserId','sourcePackageVersionId','sourcePackageCode','sourcePackageDisplayName','sourcePackageVersion','compositionMode','version','createdAt','updatedAt'].includes(key)).map(([key,value])=><div key={key}><dt><strong>{dashboardFieldLabel(key)}</strong></dt><dd>{displayValue(key,value,order.currency)}</dd></div>)}</dl></details>
    <OrderRequirementRegion requirements={requirementPage?.items??[]} derivedTotalMinor={requirementPage?.derivedTotalMinor} catalogSubtotalMinor={requirementPage?.catalogSubtotalMinor} packageAdjustmentMinor={requirementPage?.packageAdjustmentMinor} currency={typeof order?.currency==='string'?order.currency:'CAT'} onUpdate={mutable?props.onUpdateRequirement:undefined}/>
    <OrderParticipantEditor participants={participants} order={order} derivedTotalMinor={participantPage?.derivedTotalMinor} serviceCatalogOptions={props.serviceCatalogOptions} playerOptions={props.participantPlayerOptions} error={props.mutationError} onAdd={mutable?props.onAdd:undefined} onUpdate={mutable?props.onUpdate:undefined}/>
    <OrderTranscriptRegion transcript={props.data.transcript as {items?:Array<Record<string,unknown>>;nextCursor?:unknown}|undefined} state={props.transcriptState} onNext={props.onNextTranscript}/>
    <section className="subsection" aria-label="交易时间线"><h3>交易时间线</h3>
      {timeline.items.length===0?<p>暂无交易记录。</p>:<div className="table-scroll"><table className="data-table"><thead><tr><th scope="col">时间</th><th scope="col">类型</th><th scope="col">方向</th><th scope="col">金额</th><th scope="col">状态</th></tr></thead><tbody>{timeline.items.map((item)=><tr key={item.id}><td>{item.occurredAt}</td><td>{item.type}</td><td>{item.direction}</td><td>{item.amountMinor===null?'—':displayValue('amountMinor',item.amountMinor,item.currency)}</td><td>{item.status}</td></tr>)}</tbody></table></div>}
      {props.pageState?.kind==='ERROR'&&<p role="alert">后续交易记录暂时无法载入。{props.pageState.requestId?` 请求编号：${props.pageState.requestId}`:''}</p>}
      {timeline.nextCursor&&<button type="button" disabled={props.pageState?.kind==='LOADING'} onClick={()=>props.onNext?.(timeline.nextCursor!)}>加载更多记录</button>}
    </section></>;
}

function OrderTranscriptRegion({transcript,state,onNext}:{transcript?:{items?:Array<Record<string,unknown>>;nextCursor?:unknown};state?:AdminBusinessDetailState['transcriptPage'];onNext?:(cursor:string)=>void}){const items=transcript?.items??[];return <section className="subsection order-transcript" aria-label="订单频道记录"><div className="subsection-heading"><div><h3>订单频道记录（只读）</h3><p>此处只用于核对客服上下文，不能发送或修改 Discord 消息。</p></div></div>{state?.kind==='ERROR'?<p role="alert">频道记录暂时无法载入。{state.requestId?` 请求编号：${state.requestId}`:''}</p>:items.length===0?<p>暂无已采集的频道记录。</p>:<ol className="transcript-list">{items.map((item,index)=><li key={`${textValue(item.eventId)}-${index}`}><header><strong>{textValue(item.authorDisplayName)||'未知成员'}</strong><time>{formatOrderDate(item.occurredAt)}</time><span>{item.eventType==='UPDATED'?'已编辑':item.eventType==='DELETED'?'已删除':'消息'}</span></header><p>{item.deleted?'[消息已删除]':textValue(item.content)||'[无文字内容]'}</p>{Array.isArray(item.attachmentMetadata)&&item.attachmentMetadata.length>0&&<small>附件 {item.attachmentMetadata.length} 个</small>}{textValue(item.replyToMessageId)&&<small>回复消息 {textValue(item.replyToMessageId)}</small>}</li>)}</ol>}{typeof transcript?.nextCursor==='string'&&<button type="button" disabled={state?.kind==='LOADING'} onClick={()=>onNext?.(transcript.nextCursor as string)}>加载更多频道记录</button>}</section>;}

function OrderNoteEditor({note,onSubmit}:{note:string;onSubmit:(fields:Record<string,unknown>)=>void}){return <details className="advanced-order-action"><summary>编辑订单备注</summary><form className="participant-inline-form" onSubmit={(event)=>{event.preventDefault();onSubmit(formRecord(event.currentTarget));}}><label><span>当前订单备注（留空即清除）</span><textarea name="note" maxLength={1000} defaultValue={note}/></label><label><span>原因码</span><input name="reasonCode" defaultValue="SUPPORT_CORRECTION" pattern="[A-Z0-9_]{3,100}" required/></label><button type="submit">保存订单备注</button></form></details>;}

function OrderRequirementRegion({requirements,derivedTotalMinor,catalogSubtotalMinor,packageAdjustmentMinor,currency,onUpdate}:{requirements:Array<Record<string,unknown>>;derivedTotalMinor:unknown;catalogSubtotalMinor:unknown;packageAdjustmentMinor:unknown;currency:string;onUpdate?:(fields:Record<string,unknown>)=>void}){
  const active=requirements.filter((item)=>item.status!=='REMOVED');
  return <section className="subsection order-requirements" aria-label="订单项目需求"><div className="subsection-heading"><div><h3>项目需求</h3><p>老板提交的项目、时长与陪玩名额；实际接单人员在下方逐条对应。</p>{typeof packageAdjustmentMinor==='number'&&packageAdjustmentMinor!==0&&<p>目录原价 {typeof catalogSubtotalMinor==='number'?formatMinorCurrency(catalogSubtotalMinor,currency):'—'} · 套餐调整 {formatMinorCurrency(packageAdjustmentMinor,currency)}</p>}</div><strong>报价 {typeof derivedTotalMinor==='number'?formatMinorCurrency(derivedTotalMinor,currency):'—'}</strong></div>{active.length===0?<p>尚未添加项目需求。</p>:<div className="requirement-card-grid">{active.map((item)=>{const requested=Number(item.requestedPlayerCount??0);const filled=Number(item.filledPlayerCount??0);const remaining=Math.max(0,requested-filled);return <article className="requirement-detail-card" key={String(item.id)}><header><div><span>{String(item.regionDisplayName??item.region??'不限区服')}</span><h4>{String(item.gameDisplayName??item.game??'未指定游戏')} · {String(item.serviceDisplayName??item.service??'未指定服务')}</h4></div><span>{remaining===0?'名额已满':`还差 ${remaining} 位`}</span></header><dl><OrderFact label="需求编号" value={String(item.id??'—')}/><OrderFact label="套餐席位编号" value={String(item.sourcePackageSlotId??'自由搭配')}/><OrderFact label="服务目录版本" value={String(item.serviceCatalogVersionId??'—')}/><OrderFact label="席位偏好" value={textValue(item.customerNote)||'未填写'}/><OrderFact label="计费" value={`${String(item.unitCount??'—')} 单位 · ${String(item.billingUnitMinutes??'—')} 分钟/单位`}/><OrderFact label="所需人数" value={`${requested} 位`}/><OrderFact label="已接单" value={`${filled} 位`}/><OrderFact label="项目小计" value={typeof item.estimatedLinePriceMinor==='number'?formatMinorCurrency(item.estimatedLinePriceMinor,currency):'—'} strong/></dl>{onUpdate?<details className="advanced-order-action"><summary>编辑席位备注</summary><form className="participant-inline-form" onSubmit={(event)=>{event.preventDefault();onUpdate({...formRecord(event.currentTarget),requirementId:item.id,expectedRequirementVersion:item.version});}}><label><span>席位备注（留空即清除）</span><textarea name="customerNote" maxLength={500} defaultValue={String(item.customerNote??'')}/></label><label><span>原因码</span><input name="reasonCode" defaultValue="SUPPORT_CORRECTION" pattern="[A-Z0-9_]{3,100}" required/></label><button type="submit">保存席位备注</button></form></details>:null}</article>;})}</div>}</section>;
}

function OrderParticipantEditor(props:{participants:Array<Record<string,unknown>>;order?:Record<string,unknown>;derivedTotalMinor:unknown;serviceCatalogOptions:Array<Record<string,unknown>>;playerOptions:Array<Record<string,unknown>>;error?:string|null;onAdd?:(fields:Record<string,unknown>)=>void;onUpdate?:(fields:Record<string,unknown>)=>void}){
  const[editing,setEditing]=useState<string|null>(null);const currency=typeof props.order?.currency==='string'?props.order.currency:'CAT';
  return <section className="subsection order-participant-editor" aria-label="订单陪玩与项目"><div className="subsection-heading"><div><h3>陪玩与项目</h3><p>每位陪玩独立绑定项目、计费数量、价格和分成。</p></div><strong>合计 {typeof props.derivedTotalMinor==='number'?formatMinorCurrency(props.derivedTotalMinor,currency):'—'}</strong></div>
    {props.participants.length===0?<p>尚未添加陪玩明细。</p>:<div className="participant-card-grid">{props.participants.map((participant)=>{const participantId=String(participant.id);const editKey=`EDIT:${participantId}`;const reassignKey=`REASSIGN:${participantId}`;return <article className={`participant-detail-card participant-detail-card--${String(participant.status??'').toLowerCase()}`} key={participantId}><header><div><span>{String(participant.displayName??'未命名陪玩')}</span><h4>{String(participant.gameDisplayName??participant.game??'未指定游戏')} · {String(participant.serviceDisplayName??participant.service??'未指定服务')}</h4></div><span>{participant.status==='REMOVED'?'已移除':participant.readiness==='READY'?'已就绪':'未就绪'}</span></header><dl><OrderFact label="Discord Tag" value={String(participant.discordTag??'—')}/><OrderFact label="Discord 用户 ID" value={String(participant.discordUserId??'—')}/><OrderFact label="陪玩 ID" value={String(participant.playerId??'—')}/><OrderFact label="需求编号" value={String(participant.orderRequirementId??'人工添加')}/><OrderFact label="服务目录版本" value={String(participant.serviceCatalogVersionId??'—')}/><OrderFact label="区服" value={String(participant.regionDisplayName??participant.region??'不限')}/><OrderFact label="计费" value={`${String(participant.unitCount??'—')} 单位 · ${String(participant.billingUnitMinutes??'—')} 分钟/单位`}/><OrderFact label="客户价格" value={typeof participant.linePriceMinor==='number'?formatMinorCurrency(participant.linePriceMinor,currency):'—'} strong/><OrderFact label="陪玩分成" value={compensationLabel(participant,currency)}/><OrderFact label="预计收益" value={typeof participant.expectedEarningMinor==='number'?formatMinorCurrency(participant.expectedEarningMinor,currency):'—'} strong/><OrderFact label="明细版本" value={String(participant.version??'—')}/></dl>{participant.status==='ACTIVE'&&props.onUpdate?<div className="participant-card-actions"><button type="button" onClick={()=>setEditing(editing===editKey?null:editKey)}>{editing===editKey?'收起编辑':'编辑明细'}</button><button type="button" onClick={()=>setEditing(editing===reassignKey?null:reassignKey)}>{editing===reassignKey?'收起改派':'改派陪玩'}</button></div>:null}{(editing===editKey||editing===reassignKey)&&<ParticipantUpdateForm key={editing} initialAction={editing===reassignKey?'REASSIGN':'CHANGE_PRICE'} participant={participant} catalogs={props.serviceCatalogOptions} players={props.playerOptions} onSubmit={(fields)=>props.onUpdate?.({...fields,participantId:participant.id,expectedParticipantVersion:participant.version})}/>}</article>;})}</div>}
    {props.error&&<p className="form-message form-message--error" role="alert">{props.error}</p>}
    {props.onAdd&&<ParticipantAddForm players={props.playerOptions} catalogs={props.serviceCatalogOptions} onSubmit={props.onAdd}/>}</section>;
}

function ParticipantAddForm(props:{players:Array<Record<string,unknown>>;catalogs:Array<Record<string,unknown>>;onSubmit:(fields:Record<string,unknown>)=>void}){return <details className="advanced-order-action"><summary>高级操作：添加陪玩明细</summary><form className="participant-inline-form" onSubmit={(event)=>{event.preventDefault();props.onSubmit(formRecord(event.currentTarget));}}><input type="hidden" name="reasonCode" value="ADD_ORDER_PLAYER"/><label><span>陪玩</span><select name="playerId" required><option value="">请选择</option>{props.players.map((player)=><option key={String(player.playerId)} value={String(player.playerId)}>{String(player.displayName??player.discordTag??player.playerId)}</option>)}</select></label><CatalogSelect catalogs={props.catalogs}/><label><span>计费单位数</span><input name="unitCount" type="number" min="1" required/></label><label><span>明细价格（猫条）</span><input name="linePriceCat" type="number" min="0.1" step="0.1" required/></label><button className="button-primary" type="submit">添加陪玩</button></form></details>;}
function ParticipantUpdateForm(props:{participant:Record<string,unknown>;catalogs:Array<Record<string,unknown>>;players:Array<Record<string,unknown>>;initialAction:'CHANGE_PRICE'|'REASSIGN';onSubmit:(fields:Record<string,unknown>)=>void}){const[action,setAction]=useState<'CHANGE_PRICE'|'CHANGE_PROJECT'|'REASSIGN'|'REMOVE'>(props.initialAction);return <form className="participant-inline-form" onSubmit={(event)=>{event.preventDefault();props.onSubmit(formRecord(event.currentTarget));}}><label><span>操作</span><select name="action" value={action} onChange={(event)=>setAction(event.currentTarget.value as typeof action)}><option value="CHANGE_PRICE">修改价格</option><option value="CHANGE_PROJECT">更换项目</option><option value="REASSIGN">改派陪玩</option><option value="REMOVE">移除陪玩</option></select></label>{action==='REASSIGN'?<label><span>新陪玩</span><select name="playerId" required><option value="">请选择</option>{props.players.map((player)=><option key={String(player.playerId)} value={String(player.playerId)}>{String(player.displayName??player.discordTag??player.playerId)}</option>)}</select></label>:null}{action==='CHANGE_PROJECT'?<><CatalogSelect catalogs={props.catalogs} defaultValue={String(props.participant.serviceCatalogVersionId??'')}/><label><span>计费单位数</span><input name="unitCount" type="number" min="1" defaultValue={Number(props.participant.unitCount??1)}/></label></>:null}{action==='CHANGE_PROJECT'||action==='CHANGE_PRICE'?<label><span>明细价格（猫条）</span><input name="linePriceCat" type="number" min="0.1" step="0.1" defaultValue={minorToCatInput(props.participant.linePriceMinor??1)}/></label>:null}<label><span>原因码</span><input key={action} name="reasonCode" defaultValue={action==='REASSIGN'?'PLAYER_UNAVAILABLE':'UPDATE_ORDER_PLAYER'} pattern="[A-Z0-9_]{3,100}" required/></label><button type="submit">保存明细</button></form>;}
function CatalogSelect({catalogs,defaultValue}:{catalogs:Array<Record<string,unknown>>;defaultValue?:string}){return <label><span>服务项目</span><select name="serviceCatalogVersionId" required defaultValue={defaultValue??''}><option value="">请选择</option>{catalogs.map((catalog)=><option key={String(catalog.id)} value={String(catalog.id)}>{`${String(catalog.gameDisplayName??catalog.game)} · ${String(catalog.serviceDisplayName??catalog.service)}${catalog.regionDisplayName?` · ${String(catalog.regionDisplayName)}`:''}`}</option>)}</select></label>;}
function formRecord(form:HTMLFormElement){return Object.fromEntries(Array.from(new FormData(form).entries()).filter((entry):entry is [string,string]=>typeof entry[1]==='string'));}
function compensationLabel(participant:Record<string,unknown>,currency:string){if(participant.compensationType==='PERCENT_BPS'&&typeof participant.compensationValue==='number')return `${(participant.compensationValue/100).toFixed(2)}% · ${participant.compensationSource==='PLAYER_OVERRIDE'?'个人规则':'项目默认'}`;if(typeof participant.compensationValue==='number')return `${formatMinorCurrency(participant.compensationValue,currency)}/单位 · ${participant.compensationSource==='PLAYER_OVERRIDE'?'个人规则':'项目默认'}`;return '—';}

function UserConsumptionRegion(props: { consumptions: NonNullable<AdminBusinessDetailState['consumptions']>; onNext?: (cursor: string) => void }) {
  const { consumptions } = props;
  return <section className="subsection" aria-label="消费记录">
    <h3>消费记录</h3>
    {consumptions.kind === 'LOADING' && <p aria-busy="true">正在载入消费记录...</p>}
    {consumptions.kind === 'ERROR' && <p role="alert">消费记录暂时无法载入。{consumptions.requestId ? ` 请求编号：${consumptions.requestId}` : ''}</p>}
    {consumptions.kind === 'EMPTY' && <p>暂无消费记录。</p>}
    {consumptions.items.length > 0 && <div className="table-scroll"><table className="data-table"><thead><tr><th scope="col">类型</th><th scope="col">金额</th><th scope="col">状态</th></tr></thead><tbody>{consumptions.items.map((item, index) => <tr key={typeof item.id === 'string' ? item.id : index}><td>{displayValue('type', item.type, item.currency)}</td><td>{displayValue('amountMinor', item.amountMinor, item.currency)}</td><td>{displayValue('status', item.status, item.currency)}</td></tr>)}</tbody></table></div>}
    {consumptions.nextCursor && <button type="button" disabled={consumptions.kind === 'LOADING'} onClick={() => props.onNext?.(consumptions.nextCursor!)}>加载更多消费记录</button>}
  </section>;
}
