import {useEffect,useMemo,useState,type FormEvent} from 'react';
import {createDashboardApiClient,type DashboardCapabilities} from './dashboard-shell.js';
import {botConfigBooleanFields,botConfigChannelFields,botConfigLabels,buildBotConfigChange,visibleBotConfigFields} from './bot-config-dashboard.js';
type Snapshot={guildId:string;version:number;values:Record<string,string|number|boolean|null>;manageableFields:string[];updatedAt:string};
export function BotConfigPage({capabilities}:{capabilities:DashboardCapabilities}){const api=useMemo(()=>createDashboardApiClient(),[]);const[snapshot,setSnapshot]=useState<Snapshot|null>(null);const[field,setField]=useState('');const[value,setValue]=useState('');const[reason,setReason]=useState('');const[status,setStatus]=useState('LOADING');const[message,setMessage]=useState<string|null>(null);const guildId=capabilities.guildId??'';
  async function load(){setStatus('LOADING');try{const response=await api.get(`/api/v1/admin/bot-config?guildId=${encodeURIComponent(guildId)}`);const body=await response.json().catch(()=>null) as {data?:Snapshot;error?:{message?:string}}|null;if(!response.ok||!body?.data){setStatus('ERROR');setMessage(body?.error?.message??'Bot 配置无法载入。');return;}const manageableFields=visibleBotConfigFields(body.data.manageableFields);if(manageableFields.length===0){setStatus('ERROR');setMessage('当前 API 未返回可用的 P0 配置字段。');return;}const next={...body.data,manageableFields};setSnapshot(next);const first=manageableFields[0]!;setField(first);setValue(displayInput(next.values[first]));setStatus('READY');}catch{setStatus('ERROR');setMessage('网络请求失败，Bot 配置无法载入。');}}
  useEffect(()=>{if(guildId)void load();else{setStatus('ERROR');setMessage('当前会话缺少 Guild 上下文。');}},[guildId]);
  function choose(next:string){setField(next);setValue(displayInput(snapshot?.values[next]));setMessage(null);}
  async function submit(event:FormEvent){event.preventDefault();if(!snapshot||status!=='READY')return;setStatus('SAVING');setMessage(null);try{const changes=buildBotConfigChange(field,value);const preview=await api.post('/api/v1/admin/bot-config/validate',{guildId,expectedVersion:snapshot.version,changes,reason});const previewBody=await preview.json().catch(()=>null) as {data?:{mayApply?:boolean;validationToken?:string;errors?:Array<{message?:string}>};error?:{message?:string}}|null;if(!preview.ok||!previewBody?.data?.mayApply||!previewBody.data.validationToken){setStatus('READY');setMessage(previewBody?.error?.message??previewBody?.data?.errors?.[0]?.message??'配置预检未通过。');return;}const update=await api.patch('/api/v1/admin/bot-config',{guildId,expectedVersion:snapshot.version,changes,reason,validationToken:previewBody.data.validationToken});const updateBody=await update.json().catch(()=>null) as {error?:{message?:string}}|null;if(!update.ok){setStatus('READY');setMessage(updateBody?.error?.message??'配置未保存，请刷新后重试。');return;}await load();setReason('');setMessage('配置已通过预检并保存。');}catch(error){setStatus('READY');setMessage(error instanceof Error?error.message:'网络请求失败，配置未保存。');}}
  async function testDelivery(){if(!snapshot||status!=='READY'||!botConfigChannelFields.has(field)||typeof snapshot.values[field]!=='string')return;setStatus('TESTING');setMessage(null);try{const response=await api.post('/api/v1/admin/bot-config/test-delivery',{guildId,expectedVersion:snapshot.version,channelField:field,channelId:snapshot.values[field],reason:reason||'DASHBOARD_CONFIG_DELIVERY_TEST'});const body=await response.json().catch(()=>null) as {data?:{messageId?:string};error?:{message?:string}}|null;setMessage(response.ok?`测试消息已投递：${body?.data?.messageId??'成功'}`:body?.error?.message??'测试投递失败。');}catch{setMessage('网络请求失败，测试消息未投递。');}finally{setStatus('READY');}}
  return <section className="dashboard-page" aria-labelledby="bot-config-title"><header className="page-heading"><div><span className="page-eyebrow">BOT OPERATIONS</span><h1 id="bot-config-title">Bot 配置</h1><p>所有变更先由服务端校验 Discord 对象与权限，再使用版本令牌原子保存。</p></div></header>{status==='LOADING'?<div className="state-card" aria-busy="true">正在载入...</div>:status==='ERROR'?<div className="state-card state-card--error" role="alert">{message}</div>:snapshot&&<><section className="content-panel"><dl className="definition-list"><div><dt>Guild</dt><dd>{snapshot.guildId}</dd></div><div><dt>版本</dt><dd>{snapshot.version}</dd></div><div><dt>最近更新</dt><dd>{new Date(snapshot.updatedAt).toLocaleString('zh-CN')}</dd></div><div><dt>可管理字段</dt><dd>{snapshot.manageableFields.length} 项</dd></div></dl></section><form className="content-panel form-grid" aria-label="Bot 配置编辑" onSubmit={submit}><label className="field field--full"><span>配置项</span><select value={field} disabled={status!=='READY'} onChange={event=>choose(event.currentTarget.value)}>{snapshot.manageableFields.map(name=><option key={name} value={name}>{botConfigLabels[name]??name}</option>)}</select></label><ConfigValueField field={field} value={value} setValue={setValue}/><label className="field field--full"><span>变更原因</span><textarea required minLength={3} maxLength={1000} disabled={status!=='READY'} value={reason} onChange={event=>setReason(event.currentTarget.value)} placeholder="说明业务请求、核对结果和回滚依据。"/></label><div className="form-actions field--full"><button className="button-primary" type="submit" disabled={status!=='READY'}>{status==='SAVING'?'校验并保存中...':'校验并保存'}</button>{botConfigChannelFields.has(field)&&<button type="button" disabled={status!=='READY'} onClick={()=>void testDelivery()}>{status==='TESTING'?'测试投递中...':'测试当前频道投递'}</button>}</div></form>{message&&<p className="status-message" role="status">{message}</p>}</>}</section>;}
function ConfigValueField({field,value,setValue}:{field:string;value:string;setValue:(value:string)=>void}){if(botConfigBooleanFields.has(field))return <label className="field"><span>值</span><select value={value} onChange={event=>setValue(event.currentTarget.value)}><option value="true">启用</option><option value="false">停用</option></select></label>;return <label className="field field--full"><span>{botConfigLabels[field]??field}</span><input required={field!=='order_archive_category_id'} value={value} onChange={event=>setValue(event.currentTarget.value)}/><small>{botConfigChannelFields.has(field)?'填写 Discord Snowflake；保存前会验证对象存在及 Bot 权限。':'按当前字段合同填写。'}</small></label>;}
function displayInput(value:unknown){return value===null||value===undefined?'':String(value);}
