import { useCallback,useEffect,useMemo,useState } from 'react';
import { BusinessTagsPage,type BusinessTagsModel } from './BusinessTagsPage.js';
import { buildBusinessTagCreateRequest,buildBusinessTagUpdateRequest,type BusinessTagRecord,type BusinessTagType } from './business-tags.js';
import { createDashboardApiClient } from './dashboard-shell.js';
const loading:BusinessTagsModel={kind:'LOADING',items:[],requestId:null};
export function BusinessTagsRoute(){const [model,setModel]=useState<BusinessTagsModel>(loading);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState<string|null>(null);const api=useMemo(()=>createDashboardApiClient(),[]);
 const load=useCallback(async()=>{setModel(loading);try{const response=await api.get('/api/v1/admin/business-tags');const body=await response.json().catch(()=>null) as {requestId?:string;data?:BusinessTagRecord[]}|null;if(response.status===403){setModel({kind:'FORBIDDEN',items:[],requestId:body?.requestId??null});return;}if(!response.ok||!Array.isArray(body?.data)){setModel({kind:'ERROR',items:[],requestId:body?.requestId??null});return;}setModel({kind:'READY',items:body.data,requestId:null});}catch{setModel({kind:'ERROR',items:[],requestId:null});}},[api]);
 useEffect(()=>{void load();},[load]);
 async function write(request:{method:'POST'|'PATCH';path:string;body:unknown}){if(busy)return;setBusy(true);setNotice(null);try{const response=request.method==='POST'?await api.post(request.path,request.body):await api.patch(request.path,request.body);const body=await response.json().catch(()=>null) as {requestId?:string;error?:{message?:string}}|null;if(!response.ok){setNotice(`${body?.error?.message??'操作失败'}${body?.requestId?` · request_id: ${body.requestId}`:''}`);return;}setNotice('业务标签库已更新。');await load();}catch{setNotice('网络请求失败，标签未变更，请稍后重试。');}finally{setBusy(false);}}
 return <BusinessTagsPage model={model} busy={busy} notice={notice} onRefresh={()=>void load()} onCreate={(value:{type:BusinessTagType;code:string;displayName:string})=>void write(buildBusinessTagCreateRequest(value))} onUpdate={(tag,value)=>void write(buildBusinessTagUpdateRequest({tag,...value}))}/>;}
