import { useState,type FormEvent } from 'react';
import { RefreshCw,Tags } from 'lucide-react';
import { businessTagTypeLabels,businessTagTypes,type BusinessTagRecord,type BusinessTagType } from './business-tags.js';

export type BusinessTagsModel={kind:'LOADING'|'READY'|'ERROR'|'FORBIDDEN';items:BusinessTagRecord[];requestId:string|null};
export function BusinessTagsPage(props:{model:BusinessTagsModel;busy?:boolean;notice?:string|null;onCreate:(value:{type:BusinessTagType;code:string;displayName:string})=>void;onUpdate:(tag:BusinessTagRecord,value:{displayName:string;enabled:boolean})=>void;onRefresh:()=>void}){
  if(props.model.kind==='LOADING')return <section className="dashboard-page"><div className="state-card"><h1>正在载入业务标签库</h1></div></section>;
  if(props.model.kind==='ERROR'||props.model.kind==='FORBIDDEN')return <section className="dashboard-page"><div className="state-card" role="alert"><h1>{props.model.kind==='FORBIDDEN'?'无权访问业务标签库':'业务标签库载入失败'}</h1>{props.model.requestId&&<code>request_id: {props.model.requestId}</code>}<button onClick={props.onRefresh}>重试</button></div></section>;
  return <section className="dashboard-page" aria-labelledby="business-tags-title">
    <header className="page-heading"><div><span className="page-eyebrow">BUSINESS TAXONOMY</span><h1 id="business-tags-title">业务标签库</h1><p>预定义游戏、陪玩服务种类、地区、语言和礼物分类。代码稳定，停用后仍保留历史引用。</p></div><button onClick={props.onRefresh}><RefreshCw size={17}/>刷新</button></header>
    {props.notice&&<div className="status-notice" role="status">{props.notice}</div>}
    <section className="action-panel"><div className="panel-heading"><div><span className="page-eyebrow">NEW TAG</span><h2>新增标签</h2></div><Tags size={22}/></div><CreateTagForm busy={props.busy} onCreate={props.onCreate}/></section>
    <div className="tag-type-grid">{businessTagTypes.map((type)=><section className="content-panel" key={type}><div className="section-heading"><div><span className="page-eyebrow">{type}</span><h2>{businessTagTypeLabels[type]}</h2></div><p>{props.model.items.filter((item)=>item.type===type).length} 项</p></div><div className="tag-list">{props.model.items.filter((item)=>item.type===type).map((tag)=><TagRow key={tag.id} tag={tag} busy={props.busy} onUpdate={props.onUpdate}/>)}</div></section>)}</div>
  </section>;
}
function CreateTagForm(props:{busy?:boolean;onCreate:(value:{type:BusinessTagType;code:string;displayName:string})=>void}){const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);props.onCreate({type:String(data.get('type')) as BusinessTagType,code:String(data.get('code')),displayName:String(data.get('displayName'))});};return <form className="form-grid" onSubmit={submit}><label className="field"><span>类型</span><select name="type">{businessTagTypes.map((type)=><option key={type} value={type}>{businessTagTypeLabels[type]}</option>)}</select></label><label className="field"><span>稳定代码</span><input name="code" required pattern="[A-Za-z][A-Za-z0-9_]{1,79}" placeholder="VALORANT"/></label><label className="field"><span>展示名称</span><input name="displayName" required maxLength={100}/></label><div className="form-actions"><button className="button-primary" disabled={props.busy}>创建标签</button></div></form>}
function TagRow(props:{tag:BusinessTagRecord;busy?:boolean;onUpdate:(tag:BusinessTagRecord,value:{displayName:string;enabled:boolean})=>void}){const [name,setName]=useState(props.tag.displayName);return <div className="tag-row"><div className="tag-row__identity"><code>{props.tag.code}</code><small>v{props.tag.version}</small></div><input aria-label={`${props.tag.code} 展示名称`} value={name} onChange={(event)=>setName(event.currentTarget.value)}/><span className={`status-pill ${props.tag.enabled?'is-active':'is-muted'}`}>{props.tag.enabled?'已启用':'已停用'}</span><div className="tag-row__actions"><button disabled={props.busy} onClick={()=>props.onUpdate(props.tag,{displayName:name,enabled:!props.tag.enabled})}>{props.tag.enabled?'停用':'启用'}</button><button disabled={props.busy||name===props.tag.displayName} onClick={()=>props.onUpdate(props.tag,{displayName:name,enabled:props.tag.enabled})}>保存名称</button></div></div>}
