import { useState } from 'react';
import { AlertTriangle, ChevronRight, RefreshCw, UserRound } from 'lucide-react';
import { formatProfileMoney, type CustomerProfileView } from './customer-profile.js';
import { CustomerWalletPanel } from './CustomerWalletPanel.js';
import type { WalletAdjustmentSubmission,WalletBalance,WalletEntry,WalletFundingSubmission } from './customer-wallet.js';

export function CustomerProfilePage(props: { model: CustomerProfileView; window: 'DAYS_30' | 'DAYS_90' | 'ALL';
  onWindowChange: (value: 'DAYS_30' | 'DAYS_90' | 'ALL') => void; onRetryModule: (module: string) => void;
  onNextOrders: (cursor: string) => void; onNextConsumptions: (cursor: string) => void;
  canAppendInternalNote?: boolean; internalNoteBusy?: boolean; internalNoteError?: string | null;
  onAppendInternalNote?: (body: string) => Promise<boolean>;
  canEditProfile?:boolean;profileEditBusy?:boolean;profileEditError?:string|null;onUpdateProfile?:(value:{displayName:string;expectedVersion:number;reasonCode:string;note:string})=>Promise<boolean>;
  wallet?:{balance:WalletBalance;entries:WalletEntry[];nextCursor?:string|null;busy:boolean};walletError?:string|null;canTopUp?:boolean;canExternalRefund?:boolean;onTopUp?:(value:WalletFundingSubmission)=>void|Promise<void>;onExternalRefund?:(value:WalletFundingSubmission)=>void|Promise<void>;canAdjustWallet?:boolean;onWalletAdjustment?:(value:WalletAdjustmentSubmission)=>void|Promise<void>;onNextWalletPage?:()=>void }) {
  const { modules } = props.model; const identity = modules.identity.kind === 'READY' ? modules.identity.data : null;
  const [internalNoteBody,setInternalNoteBody]=useState('');
  const [displayName,setDisplayName]=useState('');
  async function appendInternalNote(event:React.FormEvent){event.preventDefault();if(!props.onAppendInternalNote)return;
    if(await props.onAppendInternalNote(internalNoteBody))setInternalNoteBody('');}
  return <section className="dashboard-page profile-page" aria-labelledby="profile-title">
    <header className="page-heading"><div><span className="page-eyebrow">CUSTOMER PROFILE</span><h1 id="profile-title">客户 Profile</h1><p>{String(identity?.displayName ?? '客户资料')} · {String(identity?.status ?? '—')}</p></div><div className="page-icon" aria-hidden="true"><UserRound size={24} /></div></header>
    <div className="module-grid profile-summary-grid">
      <Module title="账户" state={modules.identity} retry={() => props.onRetryModule('identity')}><dl className="compact-definition"><dt>业务用户</dt><dd>{String(identity?.userId ?? '—')}</dd><dt>Discord</dt><dd>{String(identity?.discordUserId ?? '—')}</dd></dl>{props.canEditProfile&&props.onUpdateProfile&&identity?<form className="internal-note-form" onSubmit={async(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);if(await props.onUpdateProfile!({displayName:displayName||String(identity.displayName??''),expectedVersion:Number(identity.version),reasonCode:String(form.get('reasonCode')??''),note:String(form.get('note')??'')}))setDisplayName('');}}><label><span>客户展示名</span><input required maxLength={80} value={displayName||String(identity.displayName??'')} onChange={(event)=>setDisplayName(event.currentTarget.value)}/></label><label><span>修改原因</span><select name="reasonCode" defaultValue="CUSTOMER_REQUEST"><option value="CUSTOMER_REQUEST">客户请求纠正</option><option value="STAFF_CORRECTION">客服纠错</option></select></label><label><span>修改说明</span><textarea name="note" maxLength={500}/></label><p>仅修改业务展示名；Discord 身份、内部 ID、钱包和历史保持只读。</p><button type="submit" disabled={props.profileEditBusy}>{props.profileEditBusy?'保存中…':'保存客户名称'}</button>{props.profileEditError?<p role="alert" className="module-error">{props.profileEditError}</p>:null}</form>:null}</Module>
      <Module title="余额" state={modules.balance} retry={() => props.onRetryModule('balance')}><Balance data={'data' in modules.balance ? modules.balance.data : undefined} /></Module>
    </div>
    {props.wallet?<CustomerWalletPanel userId={String(identity?.userId??'')} {...props.wallet} canTopUp={Boolean(props.canTopUp)} canExternalRefund={Boolean(props.canExternalRefund)} onTopUp={props.onTopUp} onExternalRefund={props.onExternalRefund} canAdjust={props.canAdjustWallet} onAdjustment={props.onWalletAdjustment} onNextPage={props.onNextWalletPage}/>:null}
    {props.walletError&&<section className="content-panel" aria-label="客户钱包"><h2>客户钱包</h2><p className="module-error"><AlertTriangle size={15}/> 钱包模块载入失败</p><small>request_id: {props.walletError}</small></section>}
    <div className="content-panel statistics-panel"><div className="section-title-row"><h2>消费统计</h2><div className="segmented-control" role="group" aria-label="统计窗口">{(['DAYS_30','DAYS_90','ALL'] as const).map((value) => <button key={value} aria-pressed={props.window === value} onClick={() => props.onWindowChange(value)}>{value === 'DAYS_30' ? '30 天' : value === 'DAYS_90' ? '90 天' : '全部'}</button>)}</div></div><Statistics state={modules.statistics} retry={() => props.onRetryModule('statistics')} /></div>
    <div className="profile-detail-stack">
      <DataTable title="订单" module={modules.orders} columns={['编号','状态','服务','陪玩','金额','创建时间']} row={(item) => [item.publicId,item.status,item.serviceKey,item.playerDisplayName,formatProfileMoney(item.amountMinor,item.currency),date(item.createdAt)]} onNext={props.onNextOrders} />
      <DataTable title="资金明细" module={modules.consumptions} columns={['类型','来源','金额','币种','时间']} row={(item) => [item.type,item.sourceId,formatProfileMoney(item.amountMinor,item.currency),item.currency,date(item.occurredAt)]} onNext={props.onNextConsumptions} />
      <div className="module-grid">
        <Module title="偏好摘要" state={modules.preferences} retry={() => props.onRetryModule('preferences')}><Preference data={'data' in modules.preferences ? modules.preferences.data : undefined} /></Module>
        <Module title="内部信息" state={modules.internal} retry={() => props.onRetryModule('internal')}><div><p>{(modules.internal.riskFlags ?? []).join(' · ') || '无风险记录'}</p>
          {props.canAppendInternalNote&&props.onAppendInternalNote?<form className="internal-note-form" onSubmit={appendInternalNote}><label><span>客服内部备注</span><textarea required maxLength={2000} value={internalNoteBody} onChange={(event)=>setInternalNoteBody(event.currentTarget.value)} placeholder="记录跟进情况，仅客服可见" /></label><button type="submit" disabled={props.internalNoteBusy||!internalNoteBody.trim()}>{props.internalNoteBusy?'追加中…':'追加备注'}</button>{props.internalNoteError?<p className="module-error" role="alert">{props.internalNoteError}</p>:null}</form>:null}
          {(modules.internal.notes ?? []).map((note) => <p className="internal-note" key={String(note.id)}>{String(note.text)}<br /><small>{date(note.createdAt)}</small></p>)}</div></Module>
      </div>
    </div>
  </section>;
}

function Module(props: { title: string; state: { kind: string; requestId?: string | null }; retry: () => void; children: React.ReactNode }) { return <section className="content-panel profile-module"><div className="card-heading"><h2>{props.title}</h2>{props.state.kind === 'ERROR' && <button title="重试" aria-label={`重试${props.title}`} onClick={props.retry}><RefreshCw size={15} /></button>}</div>{props.state.kind === 'LOADING' ? <p>正在载入...</p> : props.state.kind === 'FORBIDDEN' ? <p>无权查看</p> : props.state.kind === 'ERROR' ? <><p className="module-error"><AlertTriangle size={15} /> 模块载入失败</p><small>request_id: {props.state.requestId ?? '—'}</small>{props.children}</> : props.children}</section>; }
function Balance({ data }: { data?: Record<string, unknown> }) { return data ? <dl className="compact-definition"><dt>账本</dt><dd>{formatProfileMoney(data.ledgerBalanceMinor,data.currency)}</dd><dt>预留</dt><dd>{formatProfileMoney(data.reservedMinor,data.currency)}</dd><dt>可用</dt><dd>{formatProfileMoney(data.availableMinor,data.currency)}</dd><dt>计算时间</dt><dd>{date(data.calculatedAt)}</dd></dl> : null; }
function Statistics({ state, retry }: { state: { kind: string; data?: Record<string, unknown>; requestId?: string | null }; retry: () => void }) { if (state.kind === 'ERROR') return <button onClick={retry}>重试 · {state.requestId}</button>; if (!state.data) return <p>正在载入...</p>; const values = [['订单',state.data.orderCount],['完成',state.data.completedOrderCount],['取消',state.data.cancelledOrderCount],['退款',state.data.refundCount],['订单消费',formatProfileMoney(state.data.orderSpendMinor,state.data.currency)],['礼物消费',formatProfileMoney(state.data.giftSpendMinor,state.data.currency)],['净消费',formatProfileMoney(state.data.totalConsumptionMinor,state.data.currency)],['订单均额',formatProfileMoney(state.data.averageOrderAmountMinor,state.data.currency)]]; return <dl className="metric-grid profile-metrics">{values.map(([label,value]) => <div className="metric-card" key={String(label)}><dt>{String(label)}</dt><dd>{String(value)}</dd></div>)}</dl>; }
function DataTable(props: { title: string; module: { kind: string; items: Array<Record<string, unknown>>; nextCursor: string | null; requestId?: string | null }; columns: string[]; row: (item: Record<string, unknown>) => unknown[]; onNext: (cursor: string) => void }) { return <section className="content-panel content-panel--flush profile-table"><h2>{props.title}</h2>{props.module.kind === 'LOADING' ? <p className="panel-padding">正在载入...</p> : props.module.kind === 'ERROR' ? <p className="panel-padding">载入失败 · request_id: {props.module.requestId ?? '—'}</p> : props.module.kind === 'EMPTY' ? <p className="panel-padding">暂无记录。</p> : <div className="table-scroll"><table className="data-table"><thead><tr>{props.columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{props.module.items.map((item) => <tr key={String(item.id)}>{props.row(item).map((value,index) => <td key={String(props.columns[index] ?? index)}>{String(value ?? '—')}</td>)}</tr>)}</tbody></table>{props.module.nextCursor ? <div className="pagination-bar panel-padding"><button onClick={() => props.onNext(props.module.nextCursor!)}>下一页<ChevronRight size={15} /></button></div> : null}</div>}</section>; }
function Preference({ data }: { data?: Record<string, unknown> }) { return <dl className="compact-definition"><dt>常用游戏</dt><dd>{array(data?.preferredGameKeys)}</dd><dt>常用服务</dt><dd>{array(data?.preferredServiceKeys)}</dd><dt>近期陪玩</dt><dd>{array(data?.preferredPlayerUserIds)}</dd></dl>; }
function date(value: unknown) { return typeof value === 'string' ? new Date(value).toLocaleString('zh-CN') : '—'; } function array(value: unknown) { return Array.isArray(value) && value.length ? value.join(' · ') : '—'; }
