import { AlertTriangle, ChevronRight, RefreshCw, UserRound } from 'lucide-react';
import { formatProfileMoney, type CustomerProfileView } from './customer-profile.js';

const card = { background: '#fff', border: '1px solid #d8e1e3', borderRadius: 6, padding: 16, minWidth: 0 } as const;
const iconButton = { border: '1px solid #9aabad', background: '#fff', color: '#173238', borderRadius: 6, padding: 7, display: 'inline-flex', cursor: 'pointer' } as const;

export function CustomerProfilePage(props: { model: CustomerProfileView; window: 'DAYS_30' | 'DAYS_90' | 'ALL';
  onWindowChange: (value: 'DAYS_30' | 'DAYS_90' | 'ALL') => void; onRetryModule: (module: string) => void;
  onNextOrders: (cursor: string) => void; onNextConsumptions: (cursor: string) => void }) {
  const { modules } = props.model; const identity = modules.identity.kind === 'READY' ? modules.identity.data : null;
  return <section style={{ padding: 24, minWidth: 0 }}>
    <header style={{ display: 'flex', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap', marginBottom: 18 }}><div><h1 style={{ margin: 0, fontSize: 24 }}>客户 Profile</h1><p style={{ margin: '6px 0 0', color: '#587075' }}>{String(identity?.displayName ?? '客户资料')} · {String(identity?.status ?? '—')}</p></div><UserRound size={24} /></header>
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,280px),1fr))', gap: 12, marginBottom: 12 }}>
      <Module title="账户" state={modules.identity} retry={() => props.onRetryModule('identity')}><dl style={definition}><dt>业务用户</dt><dd>{String(identity?.userId ?? '—')}</dd><dt>Discord</dt><dd>{String(identity?.discordUserId ?? '—')}</dd><dt>第三方账号</dt><dd>{String(identity?.externalAccountDisplay ?? '—')}</dd></dl></Module>
      <Module title="余额" state={modules.balance} retry={() => props.onRetryModule('balance')}><Balance data={'data' in modules.balance ? modules.balance.data : undefined} /></Module>
    </div>
    <div style={{ ...card, marginBottom: 12 }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 8, flexWrap: 'wrap' }}><h2 style={heading}>消费统计</h2><div role="group" aria-label="统计窗口">{(['DAYS_30','DAYS_90','ALL'] as const).map((value) => <button key={value} onClick={() => props.onWindowChange(value)} style={{ ...iconButton, background: props.window === value ? '#173238' : '#fff', color: props.window === value ? '#fff' : '#173238' }}>{value === 'DAYS_30' ? '30 天' : value === 'DAYS_90' ? '90 天' : '全部'}</button>)}</div></div><Statistics state={modules.statistics} retry={() => props.onRetryModule('statistics')} /></div>
    <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr)', gap: 12 }}>
      <DataTable title="订单" module={modules.orders} columns={['编号','状态','服务','陪玩','金额','创建时间']} row={(item) => [item.publicId,item.status,item.serviceKey,item.playerDisplayName,formatProfileMoney(item.amountMinor,item.currency),date(item.createdAt)]} onNext={props.onNextOrders} />
      <DataTable title="资金明细" module={modules.consumptions} columns={['类型','来源','金额','币种','时间']} row={(item) => [item.type,item.sourceId,formatProfileMoney(item.amountMinor,item.currency),item.currency,date(item.occurredAt)]} onNext={props.onNextConsumptions} />
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,280px),1fr))', gap: 12 }}>
        <Module title="偏好摘要" state={modules.preferences} retry={() => props.onRetryModule('preferences')}><Preference data={'data' in modules.preferences ? modules.preferences.data : undefined} /></Module>
        <Module title="内部信息" state={modules.internal} retry={() => props.onRetryModule('internal')}><div><p>{(modules.internal.riskFlags ?? []).join(' · ') || '无风险记录'}</p>{(modules.internal.notes ?? []).map((note) => <p key={String(note.id)} style={{ borderTop: '1px solid #e4eaeb', paddingTop: 8 }}>{String(note.text)}<br /><small>{date(note.createdAt)}</small></p>)}</div></Module>
      </div>
    </div>
  </section>;
}

function Module(props: { title: string; state: { kind: string; requestId?: string | null }; retry: () => void; children: React.ReactNode }) { return <section style={card}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 8 }}><h2 style={heading}>{props.title}</h2>{props.state.kind === 'ERROR' && <button title="重试" aria-label={`重试${props.title}`} style={iconButton} onClick={props.retry}><RefreshCw size={15} /></button>}</div>{props.state.kind === 'LOADING' ? <p>正在载入...</p> : props.state.kind === 'FORBIDDEN' ? <p>无权查看</p> : props.state.kind === 'ERROR' ? <><p style={{ color: '#8a5100' }}><AlertTriangle size={15} /> 模块载入失败</p><small>request_id: {props.state.requestId ?? '—'}</small>{props.children}</> : props.children}</section>; }
function Balance({ data }: { data?: Record<string, unknown> }) { return data ? <dl style={definition}><dt>Provider</dt><dd>{formatProfileMoney(data.providerBalanceMinor,data.currency)}</dd><dt>预留</dt><dd>{formatProfileMoney(data.reservedMinor,data.currency)}</dd><dt>可用</dt><dd>{formatProfileMoney(data.availableMinor,data.currency)}</dd><dt>更新时间</dt><dd>{date(data.fetchedAt)}</dd></dl> : null; }
function Statistics({ state, retry }: { state: { kind: string; data?: Record<string, unknown>; requestId?: string | null }; retry: () => void }) { if (state.kind === 'ERROR') return <button style={iconButton} onClick={retry}>重试 · {state.requestId}</button>; if (!state.data) return <p>正在载入...</p>; const values = [['订单',state.data.orderCount],['完成',state.data.completedOrderCount],['取消',state.data.cancelledOrderCount],['退款',state.data.refundCount],['订单消费',formatProfileMoney(state.data.orderSpendMinor,state.data.currency)],['礼物消费',formatProfileMoney(state.data.giftSpendMinor,state.data.currency)],['净消费',formatProfileMoney(state.data.totalConsumptionMinor,state.data.currency)],['订单均额',formatProfileMoney(state.data.averageOrderAmountMinor,state.data.currency)]]; return <dl style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(120px,1fr))', gap: 10 }}>{values.map(([label,value]) => <div key={String(label)}><dt style={{ color: '#64787c', fontSize: 12 }}>{String(label)}</dt><dd style={{ margin: '3px 0 0', fontWeight: 650 }}>{String(value)}</dd></div>)}</dl>; }
function DataTable(props: { title: string; module: { kind: string; items: Array<Record<string, unknown>>; nextCursor: string | null; requestId?: string | null }; columns: string[]; row: (item: Record<string, unknown>) => unknown[]; onNext: (cursor: string) => void }) { return <section style={{ ...card, padding: 0 }}><h2 style={{ ...heading, padding: '16px 16px 8px' }}>{props.title}</h2>{props.module.kind === 'LOADING' ? <p style={{ padding: 16 }}>正在载入...</p> : props.module.kind === 'ERROR' ? <p style={{ padding: 16 }}>载入失败 · request_id: {props.module.requestId ?? '—'}</p> : props.module.kind === 'EMPTY' ? <p style={{ padding: 16 }}>暂无记录。</p> : <div style={{ overflowX: 'auto' }}><table style={{ width: '100%', minWidth: 720, borderCollapse: 'collapse' }}><thead><tr>{props.columns.map((column) => <th key={column} style={cell}>{column}</th>)}</tr></thead><tbody>{props.module.items.map((item) => <tr key={String(item.id)}>{props.row(item).map((value,index) => <td key={String(props.columns[index] ?? index)} style={cell}>{String(value ?? '—')}</td>)}</tr>)}</tbody></table>{props.module.nextCursor ? <button style={{ ...iconButton, margin: 12 }} onClick={() => props.onNext(props.module.nextCursor!)}>下一页<ChevronRight size={15} /></button> : null}</div>}</section>; }
function Preference({ data }: { data?: Record<string, unknown> }) { return <dl style={definition}><dt>常用游戏</dt><dd>{array(data?.preferredGameKeys)}</dd><dt>常用服务</dt><dd>{array(data?.preferredServiceKeys)}</dd><dt>近期陪玩</dt><dd>{array(data?.preferredPlayerUserIds)}</dd></dl>; }
const heading = { margin: 0, fontSize: 16, letterSpacing: 0 } as const; const definition = { display: 'grid', gridTemplateColumns: '110px minmax(0,1fr)', gap: '8px 12px', margin: '12px 0 0', overflowWrap: 'anywhere' } as const;
const cell = { textAlign: 'left', padding: '10px 12px', borderBottom: '1px solid #e4eaeb', fontSize: 13 } as const;
function date(value: unknown) { return typeof value === 'string' ? new Date(value).toLocaleString('zh-CN') : '—'; } function array(value: unknown) { return Array.isArray(value) && value.length ? value.join(' · ') : '—'; }
