const fieldLabels: Readonly<Record<string, string>> = {
  id: '编号',
  publicId: '业务编号',
  userId: '用户编号',
  orderId: '订单编号',
  playerId: '陪玩编号',
  serviceId: '服务编号',
  giftId: '礼物编号',
  guildId: '服务器编号',
  actorId: '操作者编号',
  actorLevel: '操作者级别',
  actorSource: '操作者来源',
  actorStaffId: '操作员工编号',
  actorUserId: '操作用户编号',
  createdByStaffId: '创建员工编号',
  requestedByStaffId: '申请员工编号',
  requestedByUserId: '申请用户编号',
  pausedByStaffId: '暂停员工编号',
  clientId: '客户端编号',
  interactionId: '交互编号',
  targetId: '目标编号',
  targetType: '目标类型',
  requestId: '请求编号',
  approvalRequestId: '审批请求编号',
  serviceOfferingId: '服务项目编号',
  serviceCatalogId: '服务版本编号',
  serviceCatalogVersionId: '服务目录版本编号',
  sourcePackageVersionId: '来源套餐版本编号',
  sourcePackageSlotId: '来源套餐席位编号',
  sourcePackageCode: '来源套餐代码',
  sourcePackageDisplayName: '来源套餐名称',
  sourcePackageVersion: '来源套餐版本',
  compositionMode: '订单构成方式',
  giftCatalogId: '礼物版本编号',
  giftRequestId: '礼物申请编号',
  fundReservationId: '资金预留编号',
  reservationId: '预留编号',
  previewId: '预览编号',
  staffTaskId: '客服任务编号',
  senderId: '赠送人编号',
  receiverId: '接收人编号',
  customerId: '客户编号',
  ownerUserId: '账户所有者编号',
  activeOrderId: '进行中订单编号',
  channelId: '频道编号',
  panelMessageId: '面板消息编号',
  sourceId: '来源编号',
  discordUserId: 'Discord 用户编号',
  customerDiscordUserId: '老板 Discord 用户编号',
  customerDiscordTag: '老板 Discord Tag',
  playerDiscordUserId: '陪玩 Discord 用户编号',
  playerDiscordTag: '陪玩 Discord Tag',
  discordTag: 'Discord Tag',
  permissionCode: '权限代码',
  action: '操作类型',
  reason: '原因',
  reasonCode: '原因代码',
  note: '备注',
  notes: '备注',
  type: '类型',
  status: '状态',
  reviewStatus: '审核状态',
  availability: '旧状态（仅诊断）',
  discordPresence: 'Discord 在线状态',
  announcementStatus: '播报状态',
  discordRoleSyncStatus: 'Discord 身份同步状态',
  automationState: '自动化状态',
  fundAction: '资金处理方式',
  version: '版本',
  rowVersion: '数据版本',
  orderVersion: '订单版本',
  catalogVersion: '目录版本',
  reservationVersion: '预留版本',
  currentRevision: '当前修订',
  code: '代码',
  key: '配置键',
  displayName: '展示名称',
  name: '名称',
  description: '说明',
  defaultCustomerPriceMinor: '套餐默认价格',
  slots: '默认陪玩席位',
  offeringKey: '服务组合代码',
  game: '游戏',
  service: '服务类型',
  orderType: '订单类型',
  giftName: '礼物名称',
  broadcastTemplate: '播报模板',
  externalAccountDisplay: '外部账户摘要',
  currency: '币种',
  amountMinor: '金额',
  priceMinor: '价格',
  estimatedAmountMinor: '预计金额',
  customerUnitPriceMinor: '客户单价',
  playerUnitPayoutMinor: '陪玩单位收益',
  playerEarningMinor: '陪玩预计收益',
  defaultPlayerPayoutBps: '默认陪玩分成（基点）',
  ledgerBalanceMinor: '账本余额',
  reservedMinor: '预留金额',
  availableMinor: '可用余额',
  capturedMinor: '已扣金额',
  releasedMinor: '已释放金额',
  releaseAmountMinor: '预计释放金额',
  refundAmountMinor: '预计退款金额',
  integerValue: '整数值',
  billingUnitMinutes: '计费单位（分钟）',
  minimumUnits: '最低购买单位',
  unitCount: '购买单位数',
  attempts: '尝试次数',
  maxAttempts: '最大尝试次数',
  lastError: '最后错误',
  runAfter: '计划执行时间',
  occurredAt: '发生时间',
  createdAt: '创建时间',
  updatedAt: '更新时间',
  startedAt: '开始时间',
  completedAt: '完成时间',
  activatedAt: '启用时间',
  retiredAt: '停用时间',
  archivedAt: '归档时间',
  pausedAt: '暂停时间',
  resumedAt: '恢复时间',
  calculatedAt: '计算时间',
  estimatedResolutionAt: '预计处理时间',
  expiresAt: '过期时间',
  periodStart: '周期开始',
  periodEnd: '周期结束',
  enabled: '是否启用',
  active: '是否有效',
  readOnly: '只读',
  serviceKey: '服务代码',
  gameKey: '游戏代码',
  gameTags: '游戏标签',
  serviceTags: '服务标签',
  languageTags: '语言标签',
  riskFlags: '风险标记',
  preferredPlayerDiscordUserIds: '优先陪玩',
  giftCategoryTagId: '礼物分类标签',
  playerDisplayName: '陪玩名称',
  region: '地区',
  language: '语言',
  quantity: '数量',
  source: '来源',
  direction: '方向',
  entryType: '流水类型'
};

export function dashboardFieldLabel(field: string): string {
  if (/\p{Script=Han}/u.test(field)) return field;
  return fieldLabels[field] ?? `未映射字段：${field}`;
}
