const fieldLabels: Readonly<Record<string, string>> = {
  id: '编号',
  publicId: '业务编号',
  userId: '用户编号',
  orderId: '订单编号',
  playerId: '陪玩编号',
  serviceId: '服务编号',
  giftId: '礼物编号',
  guildId: '服务器编号',
  actorId: '操作者编号',
  actorLevel: '操作者级别',
  actorSource: '操作者来源',
  clientId: '客户端编号',
  interactionId: '交互编号',
  targetId: '目标编号',
  targetType: '目标类型',
  requestId: '请求编号',
  approvalRequestId: '审批请求编号',
  sourceId: '来源编号',
  discordUserId: 'Discord 用户编号',
  permissionCode: '权限代码',
  action: '操作类型',
  reason: '原因',
  reasonCode: '原因代码',
  note: '备注',
  notes: '备注',
  type: '类型',
  status: '状态',
  reviewStatus: '审核状态',
  version: '版本',
  currentRevision: '当前修订',
  code: '代码',
  key: '配置键',
  displayName: '展示名称',
  name: '名称',
  description: '说明',
  currency: '币种',
  amountMinor: '金额',
  priceMinor: '价格',
  integerValue: '整数值',
  attempts: '尝试次数',
  lastError: '最后错误',
  runAfter: '计划执行时间',
  occurredAt: '发生时间',
  createdAt: '创建时间',
  updatedAt: '更新时间',
  startedAt: '开始时间',
  completedAt: '完成时间',
  expiresAt: '过期时间',
  periodStart: '周期开始',
  periodEnd: '周期结束',
  enabled: '是否启用',
  active: '是否有效',
  readOnly: '只读',
  serviceKey: '服务代码',
  gameKey: '游戏代码',
  playerDisplayName: '陪玩名称',
  region: '地区',
  language: '语言',
  quantity: '数量',
  source: '来源',
  direction: '方向',
  entryType: '流水类型'
};

export function dashboardFieldLabel(field: string): string {
  if (/\p{Script=Han}/u.test(field)) return field;
  return fieldLabels[field] ?? '数据字段';
}

