import crypto from 'node:crypto';
import type{FastifyInstance,FastifyRequest}from'fastify';
import type{Pool,PoolClient}from'pg';
import{registerSecureReadRoute,registerSecureWriteRoute}from'./security.js';

export type ReferralProgramType='PROMOTER_FIRST_PURCHASE'|'PLAYER_LIFETIME';
export interface ReferralProgramPolicy{id:string;programType:ReferralProgramType;version:number;rewardMode:'FIXED_FIRST_PURCHASE'|'PERCENT_FIRST_PURCHASE'|'PERCENT_LIFETIME';rateBps:number|null;fixedAmountMinor:number|null;currency:string;}
export interface ReferralAttributionRecord{id:string;referredCustomerId:string;beneficiaryId:string;programType:ReferralProgramType;rewardMode:ReferralProgramPolicy['rewardMode'];rateBps:number|null;fixedAmountMinor:number|null;currency:string;status:'ACTIVE'|'FULFILLED'|'SUPERSEDED'|'REVOKED';bindingMethod:'INVITE_CODE'|'ADMIN_MANUAL'|'ADMIN_CORRECTION';boundAt:string;updatedAt:string;version:number;replacesAttributionId:string|null;}
export interface ReferralAttributionStore{listRedacted(input:{limit:number}):Promise<Array<{id:string;attentionRequired:boolean;boundAt:string;updatedAt:string;version:number}>>|Array<{id:string;attentionRequired:boolean;boundAt:string;updatedAt:string;version:number}>;get(id:string):Promise<ReferralAttributionRecord>|ReferralAttributionRecord;create(input:CreateInput):Promise<ReferralAttributionRecord>|ReferralAttributionRecord;correct(input:CorrectInput):Promise<ReferralAttributionRecord>|ReferralAttributionRecord;}
export interface ReferralQueryClient{query<Row=Record<string,unknown>>(sql:string,values?:unknown[]):Promise<{rows:Row[]}>;}
interface CreateInput{referredCustomerId:string;beneficiaryId:string;programType:ReferralProgramType;bindingMethod:'INVITE_CODE'|'ADMIN_MANUAL';reason:string;actorStaffId:string;now:Date;idempotencyKey:string;}
interface CorrectInput{id:string;expectedVersion:number;replacementBeneficiaryId:string;reason:string;actorStaffId:string;now:Date;idempotencyKey:string;}
export class ReferralError extends Error{constructor(readonly code:'NOT_FOUND'|'PERMISSION_DENIED'|'VALIDATION_ERROR'|'CONFLICT'|'REFERRAL_INELIGIBLE',message:string){super(message);this.name='ReferralError';}}

export class InMemoryReferralAttributionStore implements ReferralAttributionStore{
 readonly attributions:ReferralAttributionRecord[]=[];private readonly users:Set<string>;private readonly playerUsers:Set<string>;private readonly policies:ReferralProgramPolicy[];private readonly consumed:Set<string>;
 constructor(input:{users?:string[];playerUsers?:string[];policies?:ReferralProgramPolicy[];consumedUsers?:string[]}={}){this.users=new Set(input.users);this.playerUsers=new Set(input.playerUsers);this.policies=structuredClone(input.policies??[]);this.consumed=new Set(input.consumedUsers);}
 listRedacted(input:{limit:number}){return this.attributions.slice(0,input.limit).map(({id,boundAt,updatedAt,version,status})=>({id,attentionRequired:status==='REVOKED',boundAt,updatedAt,version}));}
 get(id:string){const value=this.attributions.find(item=>item.id===id);if(!value)throw new ReferralError('NOT_FOUND','Referral attribution was not found.');return structuredClone(value);}
 create(input:CreateInput){this.assertEligible(input.referredCustomerId,input.beneficiaryId,input.programType);const policy=this.policy(input.programType);const id=deterministicUuid(`referral:${input.idempotencyKey}`);
  const replay=this.attributions.find(item=>item.id===id);if(replay)return structuredClone(replay);const record:ReferralAttributionRecord={id,referredCustomerId:input.referredCustomerId,beneficiaryId:input.beneficiaryId,programType:input.programType,rewardMode:policy.rewardMode,rateBps:policy.rateBps,fixedAmountMinor:policy.fixedAmountMinor,currency:policy.currency,status:'ACTIVE',bindingMethod:input.bindingMethod,boundAt:input.now.toISOString(),updatedAt:input.now.toISOString(),version:1,replacesAttributionId:null};this.attributions.push(record);return structuredClone(record);}
 correct(input:CorrectInput){const previous=this.attributions.find(item=>item.id===input.id);if(!previous)throw new ReferralError('NOT_FOUND','Referral attribution was not found.');const replay=this.attributions.find(item=>item.replacesAttributionId===previous.id);if(replay)return structuredClone(replay);
  if(previous.version!==input.expectedVersion||previous.status!=='ACTIVE')throw new ReferralError('CONFLICT','Referral attribution version is stale.');this.assertBeneficiary(previous.referredCustomerId,input.replacementBeneficiaryId,previous.programType);previous.status='SUPERSEDED';previous.version+=1;previous.updatedAt=input.now.toISOString();const replacement:{[K in keyof ReferralAttributionRecord]:ReferralAttributionRecord[K]}={...structuredClone(previous),id:deterministicUuid(`referral-correction:${input.idempotencyKey}`),beneficiaryId:input.replacementBeneficiaryId,status:'ACTIVE',bindingMethod:'ADMIN_CORRECTION',boundAt:input.now.toISOString(),updatedAt:input.now.toISOString(),version:1,replacesAttributionId:previous.id};this.attributions.push(replacement);return structuredClone(replacement);}
 private policy(type:ReferralProgramType){const value=this.policies.find(item=>item.programType===type);if(!value)throw new ReferralError('REFERRAL_INELIGIBLE','No active referral program exists.');return value;}
 private assertBeneficiary(referred:string,beneficiary:string,type:ReferralProgramType){if(referred===beneficiary)throw new ReferralError('REFERRAL_INELIGIBLE','Self referral is not allowed.');if(!this.users.has(referred)||!this.users.has(beneficiary))throw new ReferralError('REFERRAL_INELIGIBLE','Referral users are not eligible.');if(type==='PLAYER_LIFETIME'&&!this.playerUsers.has(beneficiary))throw new ReferralError('REFERRAL_INELIGIBLE','The beneficiary is not an active player.');}
 private assertEligible(referred:string,beneficiary:string,type:ReferralProgramType){this.assertBeneficiary(referred,beneficiary,type);if(this.consumed.has(referred))throw new ReferralError('REFERRAL_INELIGIBLE','Referral must be bound before first consumption.');if(this.attributions.some(item=>item.referredCustomerId===referred&&item.status==='ACTIVE'))throw new ReferralError('REFERRAL_INELIGIBLE','The customer already has an active referral attribution.');}
}

export class PostgresReferralAttributionStore implements ReferralAttributionStore{
 constructor(private readonly pool:Pool){}
 async listRedacted(input:{limit:number}){const r=await this.pool.query<RedactedRow>(`SELECT id,status,row_version,bound_at,COALESCE(revoked_at,superseded_at,fulfilled_at,bound_at) AS updated_at FROM referral_attributions ORDER BY bound_at DESC,id DESC LIMIT $1`,[input.limit]);return r.rows.map(row=>({id:row.id,attentionRequired:row.status==='REVOKED',boundAt:iso(row.bound_at),updatedAt:iso(row.updated_at),version:row.row_version}));}
 get(id:string){return loadAttribution(this.pool,id);}
 async create(input:CreateInput){const client=await this.pool.connect();try{await client.query('BEGIN');const existing=await client.query<{id:string}>('SELECT id FROM referral_attributions WHERE source_reference_hash=$1',[hash(input.idempotencyKey)]);if(existing.rows[0]){const value=await loadAttribution(client,existing.rows[0].id);await client.query('COMMIT');return value;}
   await assertEligibleDb(client,input.referredCustomerId,input.beneficiaryId,input.programType);const policy=await activePolicy(client,input.programType);const id=deterministicUuid(`referral:${input.idempotencyKey}`);await client.query(`INSERT INTO referral_attributions(id,program_version_id,beneficiary_user_id,referred_user_id,status,row_version,active_attribution_key,source_type,source_reference_hash,bound_by_staff_id,eligibility_checked_at,bound_at,created_at)VALUES($1,$2,$3,$4,'ACTIVE',1,$4,$5,$6,$7,$8,$8,$8)`,[id,policy.id,input.beneficiaryId,input.referredCustomerId,input.bindingMethod,hash(input.idempotencyKey),input.actorStaffId,input.now]);const value=await loadAttribution(client,id);await client.query('COMMIT');return value;
  }catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
 async correct(input:CorrectInput){const client=await this.pool.connect();try{await client.query('BEGIN');const replay=await client.query<{id:string}>('SELECT id FROM referral_attributions WHERE source_reference_hash=$1',[hash(input.idempotencyKey)]);if(replay.rows[0]){const value=await loadAttribution(client,replay.rows[0].id);await client.query('COMMIT');return value;}
   const previous=await loadAttribution(client,input.id,true);if(previous.version!==input.expectedVersion||previous.status!=='ACTIVE')throw new ReferralError('CONFLICT','Referral attribution version is stale.');await assertBeneficiaryDb(client,previous.referredCustomerId,input.replacementBeneficiaryId,previous.programType);
   await client.query(`UPDATE referral_attributions SET status='SUPERSEDED',row_version=row_version+1,active_attribution_key=NULL,superseded_at=$2 WHERE id=$1`,[previous.id,input.now]);const policy=await activePolicy(client,previous.programType);const id=deterministicUuid(`referral-correction:${input.idempotencyKey}`);await client.query(`INSERT INTO referral_attributions(id,program_version_id,beneficiary_user_id,referred_user_id,status,row_version,active_attribution_key,source_type,source_reference_hash,bound_by_staff_id,replaces_attribution_id,eligibility_checked_at,bound_at,created_at)VALUES($1,$2,$3,$4,'ACTIVE',1,$4,'ADMIN_MANUAL',$5,$6,$7,$8,$8,$8)`,[id,policy.id,input.replacementBeneficiaryId,previous.referredCustomerId,hash(input.idempotencyKey),input.actorStaffId,previous.id,input.now]);const value=await loadAttribution(client,id);await client.query('COMMIT');return value;
  }catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
}

export function calculateReferralCommissionMinor(input:{baseAmountMinor:number;awardMode:'FIXED_MINOR'|'NET_SPEND_BPS';fixedAmountMinor:number|null;rateBps:number|null}){return input.awardMode==='FIXED_MINOR'?Math.max(0,input.fixedAmountMinor??0):Math.floor(input.baseAmountMinor*Math.max(0,input.rateBps??0)/10_000);}

export async function createEligibleReferralCommission(client:ReferralQueryClient,input:{referredUserId:string;sourceConsumptionEntryId:string;baseAmountMinor:number;currency:string;source:'ORDER'|'GIFT';now:Date}):Promise<string|null>{
 const eligibleColumn=input.source==='ORDER'?'eligible_order_spend':'eligible_gift_spend';const r=await client.query<EligibleRow>(`SELECT ra.id,ra.beneficiary_user_id,p.program_type,p.version AS program_version,p.award_mode,p.fixed_amount_minor,p.rate_bps,p.currency FROM referral_attributions ra JOIN referral_program_versions p ON p.id=ra.program_version_id WHERE ra.referred_user_id=$1 AND ra.status='ACTIVE' AND p.status='ACTIVE' AND p.${eligibleColumn}=true AND p.currency=$2 ORDER BY ra.bound_at,ra.id LIMIT 1 FOR UPDATE OF ra`,[input.referredUserId,input.currency]);const a=r.rows[0];if(!a)return null;
 const amount=calculateReferralCommissionMinor({baseAmountMinor:input.baseAmountMinor,awardMode:a.award_mode,fixedAmountMinor:a.fixed_amount_minor===null?null:Number(a.fixed_amount_minor),rateBps:a.rate_bps});if(amount<=0)return null;
 const inserted=await client.query<{id:string}>(`INSERT INTO commissions(id,referral_attribution_id,beneficiary_user_id,source_consumption_entry_id,program_type_snapshot,program_version_snapshot,award_mode_snapshot,base_amount_minor,fixed_amount_minor,rate_bps,amount_minor,currency,status,row_version,created_at,updated_at) VALUES(gen_random_uuid(),$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'PENDING',1,$12,$12) ON CONFLICT(source_consumption_entry_id) DO NOTHING RETURNING id`,[a.id,a.beneficiary_user_id,input.sourceConsumptionEntryId,a.program_type,a.program_version,a.award_mode,input.baseAmountMinor,a.fixed_amount_minor,a.rate_bps,amount,input.currency,input.now]);
 if(inserted.rows[0]&&a.program_type==='PROMOTER_FIRST_PURCHASE')await client.query(`UPDATE referral_attributions SET status='FULFILLED',row_version=row_version+1,active_attribution_key=NULL,fulfilled_at=$2 WHERE id=$1 AND status='ACTIVE'`,[a.id,input.now]);return inserted.rows[0]?.id??null;
}

export function registerReferralAttributionRoutes(server:FastifyInstance,options:{store:ReferralAttributionStore;now?:()=>Date}){if(!server.securityOptions)throw new Error('Referral routes require security options.');const security=server.securityOptions,now=options.now??(()=>new Date());
 registerSecureReadRoute(server,security,{method:'GET',url:'/api/v1/admin/referral-attributions',permission:'referral.read',requiredFeature:'REFERRALS',action:'LIST_REFERRAL_ATTRIBUTIONS',targetType:'referral_attribution',acceptedSources:['DASHBOARD','DISCORD_BOT'],handler:async(request)=>({items:await options.store.listRedacted({limit:limit(request)}),nextCursor:null}),mapError});
 registerSecureWriteRoute(server,security,{method:'POST',url:'/api/v1/admin/referral-attributions',permission:'referral.manage',requiredFeature:'REFERRALS',action:'CREATE_REFERRAL_ATTRIBUTION',targetType:'referral_attribution',acceptedSources:['DASHBOARD','DISCORD_BOT'],requiresRecentStepUp:true,successStatusCode:201,
  handler:(request,actor)=>{if(!actor.actorStaffId)throw new ReferralError('PERMISSION_DENIED','A staff actor is required.');return options.store.create({...parseCreate(request.body),actorStaffId:actor.actorStaffId,idempotencyKey:request.headers['idempotency-key'] as string,now:now()});},fingerprintBody:request=>parseCreate(request.body),mapError});
 registerSecureReadRoute(server,security,{method:'GET',url:'/api/v1/admin/referral-attributions/:referralAttributionId',permission:'referral.manage',requiredFeature:'REFERRALS',action:'GET_REFERRAL_ATTRIBUTION_CONFIDENTIAL',targetType:'referral_attribution',targetId:idParam,acceptedSources:['DASHBOARD','DISCORD_BOT'],requiresRecentStepUp:true,handler:request=>options.store.get(idParam(request)),mapError});
 registerSecureWriteRoute(server,security,{method:'PATCH',url:'/api/v1/admin/referral-attributions/:referralAttributionId',permission:'referral.manage',requiredFeature:'REFERRALS',action:'CORRECT_REFERRAL_ATTRIBUTION',targetType:'referral_attribution',targetId:idParam,acceptedSources:['DASHBOARD','DISCORD_BOT'],requiresRecentStepUp:true,
  handler:(request,actor)=>{if(!actor.actorStaffId)throw new ReferralError('PERMISSION_DENIED','A staff actor is required.');return options.store.correct({...parseCorrect(request.body),id:idParam(request),actorStaffId:actor.actorStaffId,idempotencyKey:request.headers['idempotency-key'] as string,now:now()});},fingerprintBody:request=>parseCorrect(request.body),mapError});
}

async function loadAttribution(client:Pick<Pool,'query'>|PoolClient,id:string,lock=false):Promise<ReferralAttributionRecord>{const r=await client.query<AttributionRow>(`SELECT ra.id,ra.referred_user_id,ra.beneficiary_user_id,ra.status,ra.row_version,ra.source_type,ra.replaces_attribution_id,ra.bound_at,COALESCE(ra.revoked_at,ra.superseded_at,ra.fulfilled_at,ra.bound_at) AS updated_at,p.program_type,p.award_mode,p.rate_bps,p.fixed_amount_minor,p.currency FROM referral_attributions ra JOIN referral_program_versions p ON p.id=ra.program_version_id WHERE ra.id=$1${lock?' FOR UPDATE OF ra':''}`,[id]);const row=r.rows[0];if(!row)throw new ReferralError('NOT_FOUND','Referral attribution was not found.');return{id:row.id,referredCustomerId:row.referred_user_id,beneficiaryId:row.beneficiary_user_id,programType:row.program_type,rewardMode:reward(row.program_type,row.award_mode),rateBps:row.rate_bps,fixedAmountMinor:row.fixed_amount_minor===null?null:Number(row.fixed_amount_minor),currency:row.currency,status:row.status,bindingMethod:row.replaces_attribution_id?'ADMIN_CORRECTION':row.source_type as 'INVITE_CODE'|'ADMIN_MANUAL',boundAt:iso(row.bound_at),updatedAt:iso(row.updated_at),version:row.row_version,replacesAttributionId:row.replaces_attribution_id};}
async function activePolicy(client:Pick<Pool,'query'>,type:ReferralProgramType){const r=await client.query<PolicyRow>(`SELECT id,program_type,version,award_mode,rate_bps,fixed_amount_minor,currency FROM referral_program_versions WHERE program_type=$1 AND status='ACTIVE' ORDER BY version DESC LIMIT 1 FOR SHARE`,[type]);if(!r.rows[0])throw new ReferralError('REFERRAL_INELIGIBLE','No active referral program exists.');return r.rows[0];}
async function assertEligibleDb(client:PoolClient,referred:string,beneficiary:string,type:ReferralProgramType){await assertBeneficiaryDb(client,referred,beneficiary,type);const r=await client.query(`SELECT EXISTS(SELECT 1 FROM consumption_entries WHERE user_id=$1) AS consumed,EXISTS(SELECT 1 FROM referral_attributions WHERE referred_user_id=$1 AND status='ACTIVE') AS attributed`,[referred]);if(r.rows[0]?.consumed)throw new ReferralError('REFERRAL_INELIGIBLE','Referral must be bound before first consumption.');if(r.rows[0]?.attributed)throw new ReferralError('REFERRAL_INELIGIBLE','The customer already has an active referral attribution.');}
async function assertBeneficiaryDb(client:PoolClient,referred:string,beneficiary:string,type:ReferralProgramType){if(referred===beneficiary)throw new ReferralError('REFERRAL_INELIGIBLE','Self referral is not allowed.');const r=await client.query(`SELECT count(*)::int AS users,EXISTS(SELECT 1 FROM player_profiles WHERE user_id=$2 AND review_status='ACTIVE') AS player FROM users WHERE id=ANY($1::uuid[])`,[[referred,beneficiary],beneficiary]);if(r.rows[0]?.users!==2||type==='PLAYER_LIFETIME'&&!r.rows[0]?.player)throw new ReferralError('REFERRAL_INELIGIBLE','Referral users are not eligible.');}
function parseCreate(value:unknown){const b=value as Record<string,unknown>;if(!b||hasUnknown(b,['referredCustomerId','beneficiaryId','programType','bindingMethod','inviteCode','reasonCode'])||typeof b.referredCustomerId!=='string'||typeof b.beneficiaryId!=='string'||!['PROMOTER_FIRST_PURCHASE','PLAYER_LIFETIME'].includes(String(b.programType))||!['INVITE_CODE','ADMIN_MANUAL'].includes(String(b.bindingMethod))||typeof b.reasonCode!=='string')throw new ReferralError('VALIDATION_ERROR','Referral attribution fields are invalid.');return{referredCustomerId:b.referredCustomerId,beneficiaryId:b.beneficiaryId,programType:b.programType as ReferralProgramType,bindingMethod:b.bindingMethod as 'INVITE_CODE'|'ADMIN_MANUAL',reason:b.reasonCode};}
function parseCorrect(value:unknown){const b=value as Record<string,unknown>;if(!b||hasUnknown(b,['expectedVersion','replacementBeneficiaryId','reasonCode','note'])||!Number.isInteger(b.expectedVersion)||typeof b.replacementBeneficiaryId!=='string'||typeof b.reasonCode!=='string')throw new ReferralError('VALIDATION_ERROR','Referral correction fields are invalid.');return{expectedVersion:b.expectedVersion as number,replacementBeneficiaryId:b.replacementBeneficiaryId,reason:[b.reasonCode,b.note].filter((v):v is string=>typeof v==='string').join(': ')};}
function hasUnknown(value:Record<string,unknown>,allowed:string[]){return Object.keys(value).some(key=>!allowed.includes(key));}
function idParam(request:FastifyRequest){const id=(request.params as{referralAttributionId?:unknown}).referralAttributionId;if(typeof id!=='string')throw new ReferralError('VALIDATION_ERROR','referralAttributionId is required.');return id;}
function limit(request:FastifyRequest){const n=Number((request.query as{limit?:unknown}).limit??50);if(!Number.isInteger(n)||n<1||n>100)throw new ReferralError('VALIDATION_ERROR','limit is invalid.');return n;}
function mapError(error:unknown){if(!(error instanceof ReferralError))return null;return{statusCode:error.code==='NOT_FOUND'?404:error.code==='PERMISSION_DENIED'?403:error.code==='VALIDATION_ERROR'?400:error.code==='REFERRAL_INELIGIBLE'?422:409,code:error.code,message:error.message};}
function reward(type:ReferralProgramType,mode:'FIXED_MINOR'|'NET_SPEND_BPS'):ReferralProgramPolicy['rewardMode']{return mode==='FIXED_MINOR'?'FIXED_FIRST_PURCHASE':type==='PROMOTER_FIRST_PURCHASE'?'PERCENT_FIRST_PURCHASE':'PERCENT_LIFETIME';}
function deterministicUuid(seed:string){const b=crypto.createHash('sha256').update(seed).digest().subarray(0,16);b[6]=(b[6]&15)|80;b[8]=(b[8]&63)|128;return`${b.subarray(0,4).toString('hex')}-${b.subarray(4,6).toString('hex')}-${b.subarray(6,8).toString('hex')}-${b.subarray(8,10).toString('hex')}-${b.subarray(10).toString('hex')}`;}
function hash(value:string){return crypto.createHash('sha256').update(value).digest('hex');}function iso(value:Date|string){return value instanceof Date?value.toISOString():new Date(value).toISOString();}
interface RedactedRow{id:string;status:ReferralAttributionRecord['status'];row_version:number;bound_at:Date|string;updated_at:Date|string}interface PolicyRow{id:string;program_type:ReferralProgramType;version:number;award_mode:'FIXED_MINOR'|'NET_SPEND_BPS';rate_bps:number|null;fixed_amount_minor:string|number|bigint|null;currency:string}interface AttributionRow extends PolicyRow{referred_user_id:string;beneficiary_user_id:string;status:ReferralAttributionRecord['status'];row_version:number;source_type:string;replaces_attribution_id:string|null;bound_at:Date|string;updated_at:Date|string;}
interface EligibleRow{id:string;beneficiary_user_id:string;program_type:ReferralProgramType;program_version:number;award_mode:'FIXED_MINOR'|'NET_SPEND_BPS';fixed_amount_minor:string|number|bigint|null;rate_bps:number|null;currency:string;}
